// web/src/components/RemoteConnectWizard.vue
<script setup lang="ts">
import { ref, reactive, watch, computed } from 'vue'
import {
  Dialog,
  DialogPanel,
  TransitionRoot,
  TransitionChild,
} from '@headlessui/vue'
import {
  ServerIcon,
  CubeIcon,
  XMarkIcon,
  ArrowLeftIcon,
  FolderIcon,
  ArrowPathIcon,
  CheckIcon,
  ChevronRightIcon,
} from '@heroicons/vue/24/outline'
import { useI18n } from 'vue-i18n'
import { useChatStore } from '@/stores/chat'
import { useProjectStore } from '@/stores/project'
import { api } from '@/composables/api'
import type { RemoteMeta, SSHAlias, RemoteAuthMethod } from '@/types/api'

type Prefill = RemoteMeta & { loadTaskUuid?: string }

const { t } = useI18n()

const props = defineProps<{
  open: boolean
  prefill?: Prefill | null
}>()

const emit = defineEmits<{
  close: []
  bound: []
}>()

const store = useChatStore()
const projectStore = useProjectStore()

type Step = 'method' | 'config' | 'connecting' | 'dir'
const step = ref<Step>('method')
const method = ref<'ssh' | 'docker'>('ssh')

const form = reactive({
  host: '',
  port: 22,
  user: 'root',
  authMethod: 'key' as RemoteAuthMethod,
  password: '',
  keyPath: '~/.ssh/id_rsa',
  passphrase: '',
})

const aliases = ref<SSHAlias[]>([])
const selectedAlias = ref('')

const error = ref('')
const connectionId = ref('')
const bound = ref(false)

// Directory picker state.
const currentDir = ref('')
const dirs = ref<string[]>([])
const dirLoading = ref(false)

// Save-as-alias.
const saveAlias = ref(false)
const aliasName = ref('')

const steps = computed<{ key: Step; label: string }[]>(() => [
  { key: 'method', label: t('wizard.steps.chooseMethod') },
  { key: 'config', label: t('wizard.steps.configure') },
  { key: 'connecting', label: t('wizard.steps.connecting') },
  { key: 'dir', label: t('wizard.steps.selectDirectory') },
])
const stepIndex = computed(() => steps.value.findIndex((s) => s.key === step.value))

watch(() => props.open, (isOpen) => {
  if (!isOpen) return
  resetState()
  void loadAliases()
  if (props.prefill) {
    // A prefill that carries a known remote path is a *reconnect* (reopening a
    // remote workspace/task that was connected before). Since we never persist
    // the SSH secret, the link must be re-established — but for key/agent auth
    // (the common case) we can do it silently instead of making the user re-fill
    // the form. Fall back to the form only if the key isn't accepted.
    if (props.prefill.remotePath) {
      void autoReconnect(props.prefill)
    } else {
      applyPrefill(props.prefill)
    }
  }
})

function resetState() {
  step.value = 'method'
  method.value = 'ssh'
  form.host = ''
  form.port = 22
  form.user = 'root'
  form.authMethod = 'key'
  form.password = ''
  form.keyPath = '~/.ssh/id_rsa'
  form.passphrase = ''
  selectedAlias.value = ''
  error.value = ''
  connectionId.value = ''
  bound.value = false
  currentDir.value = ''
  dirs.value = []
  saveAlias.value = false
  aliasName.value = ''
}

function applyPrefill(p: Prefill) {
  // host may carry a port (e.g. "1.2.3.4:22"); split it out for the form.
  const colon = p.host.lastIndexOf(':')
  form.host = colon >= 0 ? p.host.slice(0, colon) : p.host
  form.port = p.port || 22
  form.user = p.user || 'root'
  // Jump straight to the config step for a reconnect.
  step.value = 'config'
}

// Seamless reconnect: try key/agent auth to the known remote path and bind
// straight to it (loading the task if one was requested), so reopening a remote
// workspace doesn't make the user walk the wizard again. Any failure (password
// auth, non-default key, passphrase, missing path) drops to the prefilled form.
async function autoReconnect(p: Prefill) {
  applyPrefill(p)
  step.value = 'connecting'
  try {
    const res = await api.remoteConnect({
      type: 'ssh',
      host: form.host.trim(),
      port: form.port || 22,
      user: form.user.trim() || 'root',
      auth_method: 'key',
      key_path: form.keyPath.trim(),
    })
    connectionId.value = res.connection_id
    currentDir.value = p.remotePath && p.remotePath !== '/' ? p.remotePath : res.remote_pwd
    await bindHere()
    // bindHere closes on success; if it failed, let the user pick a directory.
    if (!bound.value) {
      if (connectionId.value) {
        await listDir(currentDir.value)
        step.value = 'dir'
      } else {
        step.value = 'config'
      }
    }
  } catch {
    // Key/agent auth not accepted — fall back to the prefilled form (no scary
    // error; the user just chooses auth + connects manually).
    error.value = ''
    step.value = 'config'
  }
}

async function loadAliases() {
  try {
    const res = await api.sshList()
    aliases.value = res.aliases || []
  } catch {
    aliases.value = []
  }
}

function applyAlias(name: string) {
  selectedAlias.value = name
  const a = aliases.value.find((x) => x.name === name)
  if (!a) return
  // addr is "user@host" (host may include :port).
  const at = a.addr.indexOf('@')
  const user = at >= 0 ? a.addr.slice(0, at) : ''
  let host = at >= 0 ? a.addr.slice(at + 1) : a.addr
  const colon = host.lastIndexOf(':')
  if (colon >= 0) {
    form.port = parseInt(host.slice(colon + 1), 10) || 22
    host = host.slice(0, colon)
  }
  if (user) form.user = user
  form.host = host
}

function chooseMethod(m: 'ssh' | 'docker') {
  if (m === 'docker') return // disabled placeholder
  method.value = m
}

// discardConnection releases an established-but-unbound SSH connection so it
// doesn't linger in the backend's pending registry (up to its TTL).
async function discardConnection() {
  if (connectionId.value && !bound.value) {
    try { await api.remoteCancel(connectionId.value) } catch { /* ignore */ }
  }
  connectionId.value = ''
}

function backToConfig() {
  void discardConnection()
  step.value = 'config'
}

async function connect() {
  if (!form.host.trim()) {
    error.value = 'Host is required'
    return
  }
  // Drop any prior pending connection (e.g. user went back and reconnected).
  await discardConnection()
  error.value = ''
  step.value = 'connecting'
  try {
    const res = await api.remoteConnect({
      type: 'ssh',
      host: form.host.trim(),
      port: form.port || 22,
      user: form.user.trim() || 'root',
      auth_method: form.authMethod,
      password: form.authMethod === 'password' ? form.password : undefined,
      key_path: form.authMethod === 'key' ? form.keyPath.trim() : undefined,
      passphrase: form.authMethod === 'key' ? form.passphrase : undefined,
    })
    connectionId.value = res.connection_id
    await listDir(res.remote_pwd)
    step.value = 'dir'
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : 'Connection failed'
    step.value = 'config'
  }
}

async function listDir(path: string) {
  if (!connectionId.value) return
  dirLoading.value = true
  error.value = ''
  try {
    const res = await api.remoteListDir(connectionId.value, path)
    currentDir.value = res.path
    dirs.value = res.dirs
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : 'Failed to list directory'
  } finally {
    dirLoading.value = false
  }
}

function navigate(name: string) {
  if (name === '..') {
    const parts = currentDir.value.split('/')
    parts.pop()
    listDir(parts.join('/') || '/')
    return
  }
  const base = currentDir.value.endsWith('/') ? currentDir.value : currentDir.value + '/'
  listDir(base + name)
}

const binding = ref(false)
async function bindHere() {
  if (!connectionId.value || binding.value) return
  binding.value = true
  error.value = ''
  try {
    const res = await api.remoteBind(connectionId.value, currentDir.value)
    const proj = projectStore.upsertRemoteProject(res.label, {
      host: res.host,
      user: res.user,
      port: res.port,
      remotePath: res.remote_path,
    })
    projectStore.setActive(proj.id)
    bound.value = true
    connectionId.value = '' // ownership transferred; do not cancel on close

    if (saveAlias.value && aliasName.value.trim()) {
      const addr = `${res.user}@${res.host}`
      try {
        await api.remoteSaveAlias(aliasName.value.trim(), addr, res.remote_path)
      } catch (e: unknown) {
        console.error('Failed to save SSH alias:', e)
      }
    }

    await store.resetToWelcomeAfterSwitch()
    if (props.prefill?.loadTaskUuid) {
      await store.loadSession(props.prefill.loadTaskUuid)
    }
    emit('bound')
    emit('close')
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : 'Failed to bind workspace'
  } finally {
    binding.value = false
  }
}

function close() {
  void discardConnection()
  emit('close')
}
</script>

<template>
  <TransitionRoot :show="open" as="template">
    <Dialog class="relative z-50" @close="close">
      <TransitionChild
        enter="ease-out duration-150" enter-from="opacity-0" enter-to="opacity-100"
        leave="ease-in duration-100" leave-from="opacity-100" leave-to="opacity-0"
      >
        <div class="fixed inset-0" style="background: var(--backdrop); backdrop-filter: blur(6px)" />
      </TransitionChild>

      <!-- Native title-bar drag strip — the blurred backdrop covers the shell's
           own drag band, so without this the macOS window can't be dragged while
           the wizard is open. Rendered only inside is-tauri-macos. -->
      <div class="titlebar-drag" data-tauri-drag-region aria-hidden="true" />

      <div class="fixed inset-0 flex items-center justify-center p-4">
        <TransitionChild
          enter="ease-out duration-150" enter-from="opacity-0 translate-y-2" enter-to="opacity-100 translate-y-0"
          leave="ease-in duration-100" leave-from="opacity-100 translate-y-0" leave-to="opacity-0 translate-y-2"
        >
          <DialogPanel class="rcw">
            <!-- Step rail -->
            <div class="rcw-rail">
              <div class="rcw-rail-title">{{ t('wizard.title') }}</div>
              <ol class="rcw-steps">
                <li
                  v-for="(s, i) in steps"
                  :key="s.key"
                  class="rcw-step"
                  :class="{ done: i < stepIndex, current: i === stepIndex }"
                >
                  <span class="rcw-step-dot">
                    <CheckIcon v-if="i < stepIndex" class="w-3 h-3" />
                    <span v-else>{{ i + 1 }}</span>
                  </span>
                  <span class="rcw-step-label">{{ s.label }}</span>
                </li>
              </ol>
            </div>

            <!-- Content -->
            <div class="rcw-body">
              <button class="rcw-close" @click="close"><XMarkIcon class="w-4 h-4" /></button>

              <!-- Step 1: method -->
              <template v-if="step === 'method'">
                <h3 class="rcw-h">{{ t('wizard.chooseMethod') }}</h3>
                <p class="rcw-sub">{{ t('wizard.pickMethodDesc') }}</p>
                <div class="rcw-methods">
                  <button class="rcw-method" :class="{ active: method === 'ssh' }" @click="chooseMethod('ssh')">
                    <ServerIcon class="w-5 h-5" />
                    <span class="rcw-method-name">{{ t('wizard.ssh') }}</span>
                    <span class="rcw-method-desc">{{ t('wizard.remoteHost') }}</span>
                  </button>
                  <button class="rcw-method disabled" disabled :title="t('wizard.comingSoon')">
                    <CubeIcon class="w-5 h-5" />
                    <span class="rcw-method-name">{{ t('wizard.docker') }}</span>
                    <span class="rcw-method-desc">{{ t('wizard.comingSoon') }}</span>
                  </button>
                </div>
                <div class="rcw-foot">
                  <span />
                  <button class="rcw-primary" @click="step = 'config'">{{ t('wizard.next') }} <ChevronRightIcon class="w-3.5 h-3.5" /></button>
                </div>
              </template>

              <!-- Step 2: config -->
              <template v-else-if="step === 'config' || step === 'connecting'">
                <h3 class="rcw-h">{{ t('wizard.sshConnection') }}</h3>
                <p class="rcw-sub">{{ t('wizard.sshDesc') }}</p>

                <div v-if="error" class="rcw-error">{{ error }}</div>

                <div v-if="aliases.length > 0" class="rcw-field">
                  <label>{{ t('settings.ssh.savedAlias') }}</label>
                  <select :value="selectedAlias" class="rcw-input" @change="applyAlias(($event.target as HTMLSelectElement).value)">
                    <option value="">{{ t('settings.ssh.noAlias') }}</option>
                    <option v-for="a in aliases" :key="a.name" :value="a.name">{{ a.name }} — {{ a.addr }}</option>
                  </select>
                </div>

                <div class="rcw-row">
                  <div class="rcw-field grow">
                    <label>{{ t('settings.ssh.host') }}</label>
                    <input v-model="form.host" class="rcw-input" :placeholder="t('wizard.hostPlaceholder')" :disabled="step === 'connecting'" />
                  </div>
                  <div class="rcw-field port">
                    <label>{{ t('settings.ssh.port') }}</label>
                    <input v-model.number="form.port" type="number" class="rcw-input" :disabled="step === 'connecting'" />
                  </div>
                </div>

                <div class="rcw-row">
                  <div class="rcw-field grow">
                    <label>{{ t('settings.ssh.user') }}</label>
                    <input v-model="form.user" class="rcw-input" :placeholder="t('wizard.userPlaceholder')" :disabled="step === 'connecting'" />
                  </div>
                  <div class="rcw-field">
                    <label>{{ t('wizard.auth') }}</label>
                    <div class="rcw-seg">
                      <button :class="{ on: form.authMethod === 'password' }" :disabled="step === 'connecting'" @click="form.authMethod = 'password'">{{ t('settings.ssh.password') }}</button>
                      <button :class="{ on: form.authMethod === 'key' }" :disabled="step === 'connecting'" @click="form.authMethod = 'key'">{{ t('settings.ssh.key') }}</button>
                    </div>
                  </div>
                </div>

                <template v-if="form.authMethod === 'password'">
                  <div class="rcw-field">
                    <label>{{ t('settings.ssh.password') }}</label>
                    <input v-model="form.password" type="password" class="rcw-input" :disabled="step === 'connecting'" />
                  </div>
                </template>
                <template v-else>
                  <div class="rcw-field">
                    <label>{{ t('settings.ssh.privateKeyPath') }}</label>
                    <input v-model="form.keyPath" class="rcw-input mono" placeholder="~/.ssh/id_rsa" :disabled="step === 'connecting'" />
                  </div>
                  <div class="rcw-field">
                    <label>{{ t('settings.ssh.passphrase') }}</label>
                    <input v-model="form.passphrase" type="password" class="rcw-input" :disabled="step === 'connecting'" />
                  </div>
                </template>

                <div class="rcw-foot">
                  <button class="rcw-ghost" :disabled="step === 'connecting'" @click="step = 'method'">{{ t('common.back') }}</button>
                  <button class="rcw-primary" :disabled="step === 'connecting'" @click="connect">
                    <ArrowPathIcon v-if="step === 'connecting'" class="w-3.5 h-3.5 spin" />
                    {{ step === 'connecting' ? t('wizard.connecting') : t('wizard.connect') }}
                  </button>
                </div>
              </template>

              <!-- Step 4: directory -->
              <template v-else-if="step === 'dir'">
                <h3 class="rcw-h">{{ t('wizard.selectDirectory') }}</h3>
                <p class="rcw-sub">{{ t('wizard.dirDesc') }}</p>

                <div v-if="error" class="rcw-error">{{ error }}</div>

                <div class="rcw-dirbar">
                  <button class="rcw-back" :title="t('wizard.backToConfig')" @click="backToConfig"><ArrowLeftIcon class="w-3.5 h-3.5" /></button>
                  <span class="rcw-dir-path">{{ currentDir || '/' }}</span>
                </div>

                <div class="rcw-dirlist">
                  <div v-if="dirLoading" class="rcw-hint"><ArrowPathIcon class="w-3.5 h-3.5 spin" /> {{ t('wizard.loading') }}</div>
                  <template v-else>
                    <button
                      v-for="d in dirs"
                      :key="d"
                      class="rcw-dir-row"
                      @click="navigate(d)"
                    >
                      <FolderIcon class="w-3.5 h-3.5" />
                      <span>{{ d }}</span>
                    </button>
                    <div v-if="dirs.length === 0" class="rcw-hint">{{ t('wizard.noSubDirs') }}</div>
                  </template>
                </div>

                <label class="rcw-save">
                  <input v-model="saveAlias" type="checkbox" />
                  <span>{{ t('wizard.saveAlias') }}</span>
                  <input v-if="saveAlias" v-model="aliasName" class="rcw-input mini" :placeholder="t('wizard.aliasNamePlaceholder')" />
                </label>

                <div class="rcw-foot">
                  <button class="rcw-ghost" :disabled="binding" @click="close">{{ t('common.cancel') }}</button>
                  <button class="rcw-primary" :disabled="binding" @click="bindHere">
                    <ArrowPathIcon v-if="binding" class="w-3.5 h-3.5 spin" />
                    {{ t('wizard.useDirectory') }}
                  </button>
                </div>
              </template>
            </div>
          </DialogPanel>
        </TransitionChild>
      </div>
    </Dialog>
  </TransitionRoot>
</template>

<style scoped>
.rcw {
  display: flex;
  width: 100%;
  max-width: 760px;
  height: 520px;
  max-height: 86vh;
  overflow: hidden;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-xl, 16px);
  box-shadow: var(--shadow-lg);
}

/* Rail */
.rcw-rail {
  width: 220px;
  flex-shrink: 0;
  padding: 22px 18px;
  background: var(--color-background);
  border-right: 1px solid var(--color-border);
}
.rcw-rail-title {
  font-size: 12px;
  font-weight: 600;
  color: var(--color-muted-foreground);
  margin-bottom: 22px;
}
.rcw-steps {
  display: flex;
  flex-direction: column;
  gap: 6px;
  list-style: none;
  padding: 0;
  margin: 0;
}
.rcw-step {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 9px 10px;
  border-radius: var(--radius-lg);
  color: var(--color-muted-foreground);
}
.rcw-step.current {
  background: var(--color-surface);
  color: var(--color-foreground);
}
.rcw-step-dot {
  display: grid;
  place-items: center;
  width: 24px;
  height: 24px;
  flex-shrink: 0;
  border-radius: 50%;
  border: 1px solid var(--color-border);
  font-size: 12px;
  font-weight: 600;
}
.rcw-step.current .rcw-step-dot {
  background: var(--color-foreground);
  color: var(--color-background);
  border-color: var(--color-foreground);
}
.rcw-step.done .rcw-step-dot {
  background: var(--color-success);
  border-color: var(--color-success);
  color: var(--color-on-primary);
}
.rcw-step-label {
  font-size: 13px;
}

/* Body */
.rcw-body {
  flex: 1;
  min-width: 0;
  position: relative;
  padding: 24px 26px;
  overflow-y: auto;
}
.rcw-close {
  position: absolute;
  top: 18px;
  right: 18px;
  border: none;
  background: transparent;
  color: var(--color-muted-foreground);
  cursor: pointer;
}
.rcw-close:hover {
  color: var(--color-foreground);
}
.rcw-h {
  font-size: 18px;
  font-weight: 600;
  color: var(--color-foreground);
}
.rcw-sub {
  margin-top: 6px;
  margin-bottom: 18px;
  font-size: 12.5px;
  color: var(--color-muted-foreground);
}
.rcw-error {
  margin-bottom: 14px;
  padding: 8px 12px;
  font-size: 12px;
  border-radius: var(--radius-lg);
  color: var(--color-error-fg, #b91c1c);
  background: var(--color-error-bg, rgba(220, 38, 38, 0.08));
  border: 1px solid var(--color-error-fg, rgba(220, 38, 38, 0.3));
  word-break: break-word;
}

/* Methods */
.rcw-methods {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 14px;
}
.rcw-method {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 10px;
  padding: 20px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-xl);
  background: var(--color-background);
  cursor: pointer;
  color: var(--color-foreground);
  transition: border-color 0.15s, background 0.15s;
}
.rcw-method:hover:not(.disabled) {
  border-color: color-mix(in srgb, var(--color-foreground) 30%, transparent);
}
.rcw-method.active {
  border-color: var(--color-foreground);
  background: var(--color-surface);
}
.rcw-method.disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.rcw-method-name {
  font-size: 15px;
  font-weight: 600;
}
.rcw-method-desc {
  font-size: 12px;
  color: var(--color-muted-foreground);
}

/* Form */
.rcw-row {
  display: flex;
  gap: 12px;
}
.rcw-field {
  display: flex;
  flex-direction: column;
  gap: 5px;
  margin-bottom: 14px;
}
.rcw-field.grow {
  flex: 1;
  min-width: 0;
}
.rcw-field.port {
  width: 96px;
  flex-shrink: 0;
}
.rcw-field label {
  font-size: 12px;
  color: var(--color-muted-foreground);
}
.rcw-input {
  width: 100%;
  padding: 9px 11px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  background: var(--color-background);
  color: var(--color-foreground);
  font-size: 13px;
  outline: none;
  transition: border-color 0.15s;
}
.rcw-input:focus {
  border-color: var(--color-primary);
}
.rcw-input.mono {
  font-family: var(--font-mono);
  font-size: 12px;
}
.rcw-input.mini {
  width: 120px;
  padding: 5px 9px;
  font-size: 12px;
}
.rcw-seg {
  display: flex;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  overflow: hidden;
}
.rcw-seg button {
  padding: 8px 14px;
  border: none;
  background: var(--color-background);
  color: var(--color-muted-foreground);
  font-size: 12.5px;
  cursor: pointer;
}
.rcw-seg button.on {
  background: var(--color-foreground);
  color: var(--color-background);
}

/* Directory list */
.rcw-dirbar {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 10px;
  margin-bottom: 8px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  background: var(--color-background);
}
.rcw-back {
  display: grid;
  place-items: center;
  border: none;
  background: transparent;
  color: var(--color-muted-foreground);
  cursor: pointer;
  flex-shrink: 0;
}
.rcw-back:hover {
  color: var(--color-foreground);
}
.rcw-dir-path {
  font-family: var(--font-mono);
  font-size: 12px;
  color: var(--color-foreground);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.rcw-dirlist {
  height: 190px;
  overflow-y: auto;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  background: var(--color-background);
  padding: 4px;
}
.rcw-dir-row {
  display: flex;
  align-items: center;
  gap: 9px;
  width: 100%;
  padding: 8px 10px;
  border: none;
  background: transparent;
  border-radius: var(--radius-md);
  color: var(--color-foreground);
  font-size: 13px;
  cursor: pointer;
  text-align: left;
}
.rcw-dir-row:hover {
  background: var(--color-muted);
}
.rcw-dir-row svg {
  color: var(--color-muted-foreground);
  flex-shrink: 0;
}
.rcw-hint {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 24px;
  font-size: 12px;
  color: var(--color-muted-foreground);
}
.rcw-save {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 12px;
  font-size: 12.5px;
  color: var(--color-muted-foreground);
  cursor: pointer;
}

/* Footer */
.rcw-foot {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: 22px;
}
.rcw-primary {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 9px 18px;
  border: none;
  border-radius: var(--radius-lg);
  background: var(--color-primary);
  color: var(--color-on-primary);
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  transition: opacity 0.15s;
}
.rcw-primary:hover:not(:disabled) {
  opacity: 0.9;
}
.rcw-primary:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
.rcw-ghost {
  padding: 9px 16px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  background: transparent;
  color: var(--color-foreground);
  font-size: 13px;
  cursor: pointer;
}
.rcw-ghost:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.spin {
  animation: rcw-spin 0.8s linear infinite;
}
@keyframes rcw-spin {
  to { transform: rotate(360deg); }
}
</style>

// web-react/src/components/RemoteConnectWizard.tsx
import { useEffect, useState } from 'react'
import {
  ArrowLeftIcon,
  ArrowPathIcon,
  CheckIcon,
  CubeIcon,
  FolderIcon,
  ServerIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline'
import { useTranslation } from 'react-i18next'
import { useAppDispatch } from '../app/hooks'
import { chatActions, loadWorkspaceState, sessionActions } from '../app/store'
import { api } from '../lib/api'
import type { DockerContainer, RemoteAuthMethod, RemoteKind, SSHAlias } from '../lib/types'

type Step = 'method' | 'config' | 'docker' | 'connecting' | 'dir'

export interface RemoteConnectWizardProps {
  open: boolean
  onClose: () => void
  onBound?: () => void
}

export function RemoteConnectWizard({ open, onClose, onBound }: RemoteConnectWizardProps) {
  const { t } = useTranslation()
  const dispatch = useAppDispatch()
  const [step, setStep] = useState<Step>('method')
  const [method, setMethod] = useState<RemoteKind>('ssh')
  const [host, setHost] = useState('')
  const [port, setPort] = useState(22)
  const [user, setUser] = useState('root')
  const [authMethod, setAuthMethod] = useState<RemoteAuthMethod>('key')
  const [password, setPassword] = useState('')
  const [keyPath, setKeyPath] = useState('~/.ssh/id_rsa')
  const [passphrase, setPassphrase] = useState('')
  const [aliases, setAliases] = useState<SSHAlias[]>([])
  const [containers, setContainers] = useState<DockerContainer[]>([])
  const [containersLoading, setContainersLoading] = useState(false)
  const [connectionId, setConnectionId] = useState('')
  const [currentDir, setCurrentDir] = useState('')
  const [dirs, setDirs] = useState<string[]>([])
  const [dirLoading, setDirLoading] = useState(false)
  const [aliasName, setAliasName] = useState('')
  const [error, setError] = useState('')
  const [binding, setBinding] = useState(false)

  useEffect(() => {
    if (!open) return
    reset()
    void loadAliases()
  }, [open])

  if (!open) return null

  async function loadAliases() {
    try {
      const res = await api.sshList()
      setAliases(res.aliases || [])
    } catch {
      setAliases([])
    }
  }

  async function loadContainers() {
    setContainersLoading(true)
    setError('')
    try {
      const res = await api.dockerContainers()
      setContainers((res.containers || []).slice().sort((a, b) => {
        if (a.running !== b.running) return a.running ? -1 : 1
        return (a.name || a.id).localeCompare(b.name || b.id)
      }))
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to list containers')
      setContainers([])
    } finally {
      setContainersLoading(false)
    }
  }

  function applyAlias(alias: SSHAlias) {
    const at = alias.addr.indexOf('@')
    const nextUser = at >= 0 ? alias.addr.slice(0, at) : ''
    let nextHost = at >= 0 ? alias.addr.slice(at + 1) : alias.addr
    const colon = nextHost.lastIndexOf(':')
    if (colon >= 0) {
      setPort(parseInt(nextHost.slice(colon + 1), 10) || 22)
      nextHost = nextHost.slice(0, colon)
    }
    if (nextUser) setUser(nextUser)
    setHost(nextHost)
    if (alias.path) setAliasName(alias.name)
  }

  async function discardConnection() {
    if (!connectionId) return
    try {
      await api.remoteCancel(connectionId)
    } catch {
      // best-effort cleanup
    }
    setConnectionId('')
  }

  async function connectSSH() {
    if (!host.trim()) {
      setError('Host is required')
      return
    }
    await discardConnection()
    setError('')
    setStep('connecting')
    try {
      const res = await api.remoteConnect({
        type: 'ssh',
        host: host.trim(),
        port,
        user: user.trim() || 'root',
        auth_method: authMethod,
        password: authMethod === 'password' ? password : undefined,
        key_path: authMethod === 'key' ? keyPath.trim() : undefined,
        passphrase: authMethod === 'key' ? passphrase : undefined,
      })
      setConnectionId(res.connection_id)
      await listDir(res.connection_id, res.remote_pwd)
      setStep('dir')
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Connection failed')
      setStep('config')
    }
  }

  async function connectDocker(container: string) {
    await discardConnection()
    setError('')
    setStep('connecting')
    try {
      const res = await api.remoteConnect({ type: 'docker', container })
      setConnectionId(res.connection_id)
      await listDir(res.connection_id, res.remote_pwd)
      setStep('dir')
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Connection failed')
      setStep('docker')
    }
  }

  async function listDir(connId: string, path: string) {
    setDirLoading(true)
    setError('')
    try {
      const res = await api.remoteListDir(connId, path)
      setCurrentDir(res.path)
      setDirs(res.dirs || [])
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to list directory')
    } finally {
      setDirLoading(false)
    }
  }

  function navigate(name: string) {
    if (!connectionId) return
    if (name === '..') {
      const parent = currentDir.split('/').slice(0, -1).join('/') || '/'
      void listDir(connectionId, parent)
      return
    }
    const base = currentDir.endsWith('/') ? currentDir : `${currentDir}/`
    void listDir(connectionId, `${base}${name}`)
  }

  async function bindHere() {
    if (!connectionId || binding) return
    setBinding(true)
    setError('')
    try {
      const res = await api.remoteBind(connectionId, currentDir)
      if (res.kind === 'docker') {
        const name = aliasName.trim() || res.container || 'container'
        await api.remoteSaveDockerAlias(name, res.container || '', res.remote_path).catch(() => {})
      } else {
        const addr = `${res.user}@${res.host}`
        await api.remoteSaveAlias(aliasName.trim() || addr, addr, res.remote_path).catch(() => {})
      }
      setConnectionId('')
      dispatch(chatActions.clearChat())
      dispatch(sessionActions.setProjectPath(res.label || res.pwd))
      dispatch(sessionActions.setCurrentSession(''))
      await dispatch(loadWorkspaceState())
      onBound?.()
      close()
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to bind workspace')
    } finally {
      setBinding(false)
    }
  }

  function reset() {
    setStep('method')
    setMethod('ssh')
    setHost('')
    setPort(22)
    setUser('root')
    setAuthMethod('key')
    setPassword('')
    setKeyPath('~/.ssh/id_rsa')
    setPassphrase('')
    setAliases([])
    setContainers([])
    setConnectionId('')
    setCurrentDir('')
    setDirs([])
    setAliasName('')
    setError('')
    setBinding(false)
  }

  function close() {
    void discardConnection()
    onClose()
  }

  return (
    <div className="fixed inset-0 z-[var(--z-modal)] flex items-center justify-center p-4" role="dialog" aria-modal="true">
      <div className="absolute inset-0 bg-[var(--backdrop)] backdrop-blur-[6px]" onClick={close} />
      <div className="titlebar-drag" data-tauri-drag-region aria-hidden="true" />
      <div className="relative flex max-h-[88vh] w-full max-w-[640px] flex-col overflow-hidden rounded-[var(--radius-2xl)] border border-[var(--color-border)] bg-[var(--color-surface)] shadow-[var(--shadow-lg)]">
        <header className="flex items-center justify-between border-b border-[var(--color-border)] px-5 py-4">
          <div>
            <h2 className="text-base font-semibold text-[var(--color-foreground)]">{t('nav.remoteConnect')}</h2>
            <p className="mt-1 text-xs text-[var(--color-muted-foreground)]">{t('wizard.pickMethodDesc')}</p>
          </div>
          <button type="button" onClick={close} aria-label={t('common.close')} className="grid h-8 w-8 place-items-center rounded-[var(--radius-md)] text-[var(--color-muted-foreground)] hover:bg-[var(--color-muted)]">
            <XMarkIcon className="h-4 w-4" />
          </button>
        </header>

        <div className="min-h-0 flex-1 overflow-y-auto p-5">
          {step === 'method' && (
            <div className="grid grid-cols-2 gap-3">
              <MethodCard active={method === 'ssh'} Icon={ServerIcon} title="SSH" desc={t('wizard.sshDesc')} onClick={() => setMethod('ssh')} />
              <MethodCard active={method === 'docker'} Icon={CubeIcon} title="Docker" desc={t('wizard.dockerDesc')} onClick={() => setMethod('docker')} />
            </div>
          )}

          {step === 'config' && (
            <div className="space-y-3">
              {aliases.length > 0 && (
                <label className="block">
                  <span className="mb-1 block text-xs font-medium text-[var(--color-muted-foreground)]">{t('settings.ssh.aliases')}</span>
                  <select onChange={(e) => {
                    const alias = aliases.find((a) => a.name === e.target.value)
                    if (alias) applyAlias(alias)
                  }} className="w-full rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-background)] px-2 py-2 text-sm text-[var(--color-foreground)]">
                    <option value="">{t('settings.ssh.noAlias')}</option>
                    {aliases.map((alias) => <option key={alias.name} value={alias.name}>{alias.name} - {alias.addr}</option>)}
                  </select>
                </label>
              )}
              <div className="grid grid-cols-[1fr_90px] gap-2">
                <Field label="Host">
                  <input value={host} onChange={(e) => setHost(e.target.value)} placeholder={t('wizard.hostPlaceholder')} className={INPUT} />
                </Field>
                <Field label="Port">
                  <input value={port} onChange={(e) => setPort(Number(e.target.value) || 22)} type="number" className={INPUT} />
                </Field>
              </div>
              <Field label="User">
                <input value={user} onChange={(e) => setUser(e.target.value)} placeholder={t('wizard.userPlaceholder')} className={INPUT} />
              </Field>
              <Field label={t('wizard.auth')}>
                <select value={authMethod} onChange={(e) => setAuthMethod(e.target.value as RemoteAuthMethod)} className={INPUT}>
                  <option value="key">Key / agent</option>
                  <option value="password">Password</option>
                </select>
              </Field>
              {authMethod === 'password' ? (
                <Field label="Password">
                  <input value={password} onChange={(e) => setPassword(e.target.value)} type="password" className={INPUT} />
                </Field>
              ) : (
                <div className="grid grid-cols-2 gap-2">
                  <Field label="Key path">
                    <input value={keyPath} onChange={(e) => setKeyPath(e.target.value)} className={INPUT} />
                  </Field>
                  <Field label="Passphrase">
                    <input value={passphrase} onChange={(e) => setPassphrase(e.target.value)} type="password" className={INPUT} />
                  </Field>
                </div>
              )}
            </div>
          )}

          {step === 'docker' && (
            <div>
              <div className="mb-3 flex items-center justify-between">
                <h3 className="text-sm font-semibold text-[var(--color-foreground)]">{t('wizard.selectContainer')}</h3>
                <button type="button" onClick={() => void loadContainers()} className="inline-flex items-center gap-1.5 rounded-[var(--radius-md)] border border-[var(--color-border)] px-2 py-1 text-xs text-[var(--color-foreground)] hover:bg-[var(--color-muted)]">
                  <ArrowPathIcon className="h-3.5 w-3.5" />
                  {t('wizard.refresh')}
                </button>
              </div>
              {containersLoading ? (
                <div className="py-8 text-center text-xs text-[var(--color-muted-foreground)]">{t('wizard.loading')}</div>
              ) : containers.length === 0 ? (
                <div className="py-8 text-center text-xs text-[var(--color-muted-foreground)]">{t('wizard.noContainers')}</div>
              ) : (
                <div className="space-y-1">
                  {containers.map((container) => (
                    <button key={container.id} type="button" disabled={!container.running} onClick={() => void connectDocker(container.id || container.name)} className="flex w-full items-center gap-2 rounded-[var(--radius-md)] px-2 py-2 text-left text-sm text-[var(--color-foreground)] hover:bg-[var(--color-muted)] disabled:opacity-45">
                      <CubeIcon className="h-4 w-4 shrink-0 text-[var(--color-muted-foreground)]" />
                      <span className="min-w-0 flex-1">
                        <span className="block truncate">{container.name || container.id}</span>
                        <span className="block truncate text-[11px] text-[var(--color-muted-foreground)]">{container.status}</span>
                      </span>
                      {container.running && <span className="text-[10px] font-semibold text-[var(--color-success-fg)]">{t('wizard.running')}</span>}
                    </button>
                  ))}
                </div>
              )}
            </div>
          )}

          {step === 'connecting' && (
            <div className="flex flex-col items-center justify-center py-14 text-sm text-[var(--color-muted-foreground)]">
              <ArrowPathIcon className="mb-3 h-6 w-6 animate-spin" />
              {t('wizard.connecting')}
            </div>
          )}

          {step === 'dir' && (
            <div className="space-y-3">
              <p className="text-xs text-[var(--color-muted-foreground)]">{t('wizard.dirDesc')}</p>
              <div className="rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-background)] px-2 py-1.5 font-mono text-xs text-[var(--color-foreground)]">{currentDir}</div>
              <div className="max-h-64 overflow-y-auto rounded-[var(--radius-lg)] border border-[var(--color-border)] p-1">
                {currentDir !== '/' && <DirRow name=".." onClick={() => navigate('..')} />}
                {dirLoading ? (
                  <div className="py-8 text-center text-xs text-[var(--color-muted-foreground)]">{t('wizard.loading')}</div>
                ) : dirs.length === 0 ? (
                  <div className="py-8 text-center text-xs text-[var(--color-muted-foreground)]">{t('wizard.noSubDirs')}</div>
                ) : (
                  dirs.map((dir) => <DirRow key={dir} name={dir} onClick={() => navigate(dir)} />)
                )}
              </div>
              <Field label={t('wizard.saveAlias')}>
                <input value={aliasName} onChange={(e) => setAliasName(e.target.value)} placeholder={t('wizard.aliasNamePlaceholder')} className={INPUT} />
              </Field>
            </div>
          )}

          {error && <div className="mt-3 rounded-[var(--radius-md)] border border-[var(--color-destructive)] bg-[var(--color-error-bg)] px-3 py-2 text-xs text-[var(--color-error-fg)]">{error}</div>}
        </div>

        <footer className="flex items-center justify-between border-t border-[var(--color-border)] bg-[var(--color-muted)] px-5 py-3">
          <button type="button" onClick={() => {
            if (step === 'method') close()
            else if (step === 'dir' && method === 'ssh') setStep('config')
            else setStep('method')
          }} className="inline-flex items-center gap-1.5 rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-1.5 text-xs text-[var(--color-foreground)] hover:bg-[var(--color-background)]">
            <ArrowLeftIcon className="h-3.5 w-3.5" />
            {t('common.back')}
          </button>
          {step === 'method' && (
            <button type="button" onClick={() => {
              if (method === 'docker') {
                setStep('docker')
                void loadContainers()
              } else setStep('config')
            }} className="rounded-[var(--radius-md)] bg-[var(--color-primary)] px-3 py-1.5 text-xs font-medium text-[var(--color-on-primary)]">
              {t('wizard.next')}
            </button>
          )}
          {step === 'config' && (
            <button type="button" onClick={() => void connectSSH()} className="rounded-[var(--radius-md)] bg-[var(--color-primary)] px-3 py-1.5 text-xs font-medium text-[var(--color-on-primary)]">
              {t('wizard.connect')}
            </button>
          )}
          {step === 'dir' && (
            <button type="button" disabled={binding} onClick={() => void bindHere()} className="inline-flex items-center gap-1.5 rounded-[var(--radius-md)] bg-[var(--color-primary)] px-3 py-1.5 text-xs font-medium text-[var(--color-on-primary)] disabled:opacity-50">
              <CheckIcon className="h-3.5 w-3.5" />
              {t('wizard.useDirectory')}
            </button>
          )}
        </footer>
      </div>
    </div>
  )
}

const INPUT = 'w-full rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-background)] px-2.5 py-2 text-sm text-[var(--color-foreground)] outline-none focus:border-[var(--color-primary)]'

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="mb-1 block text-xs font-medium text-[var(--color-muted-foreground)]">{label}</span>
      {children}
    </label>
  )
}

function MethodCard({ active, Icon, title, desc, onClick }: { active: boolean; Icon: typeof ServerIcon; title: string; desc: string; onClick: () => void }) {
  return (
    <button type="button" onClick={onClick} className={`flex flex-col gap-2 rounded-[var(--radius-xl)] border p-4 text-left transition-colors hover:bg-[var(--color-muted)] ${active ? 'border-[var(--color-primary)] bg-[var(--accent-wash)]' : 'border-[var(--color-border)] bg-[var(--color-background)]'}`}>
      <Icon className="h-5 w-5 text-[var(--color-primary)]" />
      <span className="text-sm font-semibold text-[var(--color-foreground)]">{title}</span>
      <span className="text-xs leading-relaxed text-[var(--color-muted-foreground)]">{desc}</span>
    </button>
  )
}

function DirRow({ name, onClick }: { name: string; onClick: () => void }) {
  return (
    <button type="button" onClick={onClick} className="flex w-full items-center gap-2 rounded-[var(--radius-md)] px-2 py-1.5 text-left text-sm text-[var(--color-foreground)] hover:bg-[var(--color-muted)]">
      {name === '..' ? <span className="w-4 text-center font-mono text-xs">..</span> : <FolderIcon className="h-4 w-4 text-[var(--color-muted-foreground)]" />}
      <span className="min-w-0 flex-1 truncate">{name}</span>
    </button>
  )
}
