// web/src/components/BranchPicker.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import {
  CheckIcon,
  ChevronDownIcon,
  CodeBracketIcon,
  MagnifyingGlassIcon,
  PlusIcon,
} from '@heroicons/react/24/outline'
import { useTranslation } from 'react-i18next'
import { api } from '../lib/api'
import { useAppSelector } from '../app/hooks'

interface PendingSwitch {
  branch: string
  create: boolean
  files: string[]
}

const MAX_FILES = 8

export function BranchPicker({ placement = 'top' }: { placement?: 'top' | 'bottom' }) {
  const { t } = useTranslation()
  const projectPath = useAppSelector((s) => s.session.projectPath)
  const [current, setCurrent] = useState('')
  const [branches, setBranches] = useState<string[]>([])
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [creating, setCreating] = useState(false)
  const [newName, setNewName] = useState('')
  const [switching, setSwitching] = useState(false)
  const [error, setError] = useState('')
  const [pending, setPending] = useState<PendingSwitch | null>(null)
  const rootRef = useRef<HTMLDivElement | null>(null)
  const inputRef = useRef<HTMLInputElement | null>(null)

  const refresh = useCallback(async () => {
    try {
      const res = await api.gitBranches()
      setCurrent(res.current || '')
      setBranches(res.branches || [])
    } catch {
      setCurrent('')
      setBranches([])
    }
  }, [])

  useEffect(() => {
    void refresh()
  }, [refresh, projectPath])

  useEffect(() => {
    function onFocus() {
      void refresh()
    }
    function onVisible() {
      if (document.visibilityState === 'visible') void refresh()
    }
    window.addEventListener('focus', onFocus)
    document.addEventListener('visibilitychange', onVisible)
    return () => {
      window.removeEventListener('focus', onFocus)
      document.removeEventListener('visibilitychange', onVisible)
    }
  }, [refresh])

  useEffect(() => {
    if (!open) return
    function onDown(e: MouseEvent) {
      if (rootRef.current && !rootRef.current.contains(e.target as Node)) reset()
    }
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') reset()
    }
    document.addEventListener('mousedown', onDown)
    document.addEventListener('keydown', onKey)
    return () => {
      document.removeEventListener('mousedown', onDown)
      document.removeEventListener('keydown', onKey)
    }
  }, [open])

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    if (!q) return branches
    return branches.filter((b) => b.toLowerCase().includes(q))
  }, [branches, query])

  if (!current) return null

  function reset() {
    setOpen(false)
    setQuery('')
    setCreating(false)
    setNewName('')
    setError('')
    setPending(null)
  }

  async function checkout(branch: string, create = false, strategy: '' | 'stash' | 'force' = '') {
    if (!branch.trim()) return
    if (branch === current && !create) {
      reset()
      return
    }
    setSwitching(true)
    setError('')
    try {
      const res = await api.gitCheckout(branch.trim(), create, strategy)
      if (res.blocked) {
        setPending({ branch: branch.trim(), create, files: res.files || [] })
        return
      }
      setPending(null)
      setCurrent(res.branch || branch.trim())
      await refresh()
      reset()
    } catch (e) {
      setError(e instanceof Error ? e.message : t('errors.branchSwitch'))
    } finally {
      setSwitching(false)
    }
  }

  function startCreate() {
    setCreating(true)
    setNewName(query.trim())
    setTimeout(() => inputRef.current?.focus(), 0)
  }

  return (
    <div ref={rootRef} className="relative inline-flex min-w-0">
      <button
        type="button"
        disabled={switching}
        title={t('branches.current').replace('{name}', current)}
        onClick={(e) => {
          e.stopPropagation()
          setOpen((v) => !v)
        }}
        className="inline-flex h-7 max-w-[180px] items-center gap-1.5 rounded-[var(--radius-lg)] px-2 text-xs text-[var(--color-muted-foreground)] transition-colors hover:bg-[var(--color-muted)] hover:text-[var(--color-foreground)] disabled:opacity-55"
      >
        <CodeBracketIcon className="h-3.5 w-3.5 shrink-0" />
        <span className="truncate font-mono">{current}</span>
        <ChevronDownIcon className={`h-3 w-3 shrink-0 opacity-70 transition-transform ${open ? 'rotate-180' : ''}`} />
      </button>

      {open && (
        <div className={`absolute left-0 z-[var(--z-dropdown)] w-[300px] max-w-[84vw] rounded-[var(--radius-xl)] border border-[var(--color-border)] bg-[var(--color-surface)] p-1.5 shadow-[var(--shadow-lg)] ${
          placement === 'bottom' ? 'top-full mt-1' : 'bottom-full mb-1'
        }`}>
          {pending ? (
            <div className="flex flex-col gap-2 p-1">
              <div className="text-xs font-semibold text-[var(--color-foreground)]">{t('branches.confirmTitle')}</div>
              <div className="text-[11.5px] text-[var(--color-muted-foreground)]">
                {t('branches.confirmIntro').replace('{branch}', pending.branch)}
              </div>
              {pending.files.length > 0 && (
                <ul className="max-h-32 overflow-y-auto rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-muted)] p-2 font-mono text-[10.5px] text-[var(--color-foreground)]">
                  {pending.files.slice(0, MAX_FILES).map((file) => (
                    <li key={file} className="truncate">{file}</li>
                  ))}
                  {pending.files.length > MAX_FILES && (
                    <li className="text-[var(--color-muted-foreground)]">
                      {t('branches.confirmMore').replace('{count}', String(pending.files.length - MAX_FILES))}
                    </li>
                  )}
                </ul>
              )}
              {error && <div className="text-[11px] text-[var(--color-destructive)]">{error}</div>}
              <div className="flex flex-wrap gap-1.5">
                <button type="button" disabled={switching} onClick={() => void checkout(pending.branch, pending.create, 'stash')} className="rounded-[var(--radius-md)] bg-[var(--color-primary)] px-2 py-1 text-[11.5px] font-medium text-[var(--color-on-primary)] disabled:opacity-50">
                  {t('branches.confirmStash')}
                </button>
                <button type="button" disabled={switching} onClick={() => void checkout(pending.branch, pending.create, 'force')} className="rounded-[var(--radius-md)] bg-[var(--color-destructive)] px-2 py-1 text-[11.5px] font-medium text-[var(--color-on-destructive)] disabled:opacity-50">
                  {t('branches.confirmDiscard')}
                </button>
                <button type="button" disabled={switching} onClick={() => setPending(null)} className="rounded-[var(--radius-md)] border border-[var(--color-border)] px-2 py-1 text-[11.5px] text-[var(--color-foreground)] disabled:opacity-50">
                  {t('branches.confirmCancel')}
                </button>
              </div>
              <div className="text-[10.5px] leading-relaxed text-[var(--color-muted-foreground)]">{t('branches.confirmHint')}</div>
            </div>
          ) : (
            <>
              <div className="flex items-center gap-2 rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-background)] px-2 py-1.5">
                <MagnifyingGlassIcon className="h-3.5 w-3.5 text-[var(--color-muted-foreground)]" />
                <input
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder={t('branches.search')}
                  className="min-w-0 flex-1 border-none bg-transparent text-[12.5px] text-[var(--color-foreground)] outline-none"
                />
              </div>
              <div className="px-2 pb-1 pt-2 text-[10px] font-semibold uppercase tracking-[0.06em] text-[var(--color-muted-foreground)]">
                {t('branches.title')}
              </div>
              <div className="max-h-56 overflow-y-auto">
                {filtered.length === 0 ? (
                  <div className="px-2 py-3 text-xs text-[var(--color-muted-foreground)]">{t('branches.none')}</div>
                ) : (
                  filtered.map((branch) => (
                    <button
                      key={branch}
                      type="button"
                      disabled={switching}
                      onClick={() => void checkout(branch)}
                      className={`flex w-full items-center gap-2 rounded-[var(--radius-md)] px-2 py-1.5 text-left text-[12.5px] transition-colors hover:bg-[var(--color-muted)] disabled:opacity-55 ${
                        branch === current ? 'font-semibold text-[var(--color-primary)]' : 'text-[var(--color-foreground)]'
                      }`}
                    >
                      <CodeBracketIcon className="h-3.5 w-3.5 shrink-0" />
                      <span className="min-w-0 flex-1 truncate font-mono">{branch}</span>
                      {branch === current && <CheckIcon className="h-3.5 w-3.5 shrink-0" />}
                    </button>
                  ))
                )}
              </div>
              {error && <div className="px-2 py-1 text-[11px] text-[var(--color-destructive)]">{error}</div>}
              <div className="mt-1 border-t border-[var(--color-border)] pt-1">
                {!creating ? (
                  <button type="button" onClick={startCreate} className="flex w-full items-center gap-2 rounded-[var(--radius-md)] px-2 py-1.5 text-left text-xs text-[var(--color-foreground)] hover:bg-[var(--color-muted)]">
                    <PlusIcon className="h-3.5 w-3.5" />
                    {t('branches.create')}
                  </button>
                ) : (
                  <div className="flex gap-1.5">
                    <input
                      ref={inputRef}
                      value={newName}
                      onChange={(e) => setNewName(e.target.value)}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter') void checkout(newName, true)
                        if (e.key === 'Escape') setCreating(false)
                      }}
                      placeholder={t('branches.newName')}
                      className="min-w-0 flex-1 rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-background)] px-2 py-1.5 text-xs text-[var(--color-foreground)] outline-none"
                    />
                    <button type="button" disabled={!newName.trim() || switching} onClick={() => void checkout(newName, true)} className="rounded-[var(--radius-md)] bg-[var(--color-primary)] px-2 py-1.5 text-xs font-medium text-[var(--color-on-primary)] disabled:opacity-50">
                      {t('branches.createBtn')}
                    </button>
                  </div>
                )}
              </div>
            </>
          )}
        </div>
      )}
    </div>
  )
}

// web/src/components/BranchPicker.vue
<script setup lang="ts">
import { ref, computed, nextTick } from 'vue'
import { Popover, PopoverButton, PopoverPanel } from '@headlessui/vue'
import { CodeBracketIcon, MagnifyingGlassIcon, ChevronDownIcon, CheckIcon, PlusIcon } from '@heroicons/vue/24/outline'
import { useI18n } from 'vue-i18n'
import { useBranch } from '@/composables/useBranch'

withDefaults(defineProps<{
  // Open upward by default; the composer sits low in the viewport.
  placement?: 'top' | 'bottom'
}>(), { placement: 'top' })

const { current, branches, switching, error, pending, checkout, resolvePending, cancelPending } =
  useBranch()
const { t } = useI18n()

// How many at-risk files to list before collapsing into a "+N more" line.
const MAX_FILES = 8

const query = ref('')
const creating = ref(false)
const newName = ref('')
const newInput = ref<HTMLInputElement | null>(null)

const filtered = computed(() => {
  const q = query.value.trim().toLowerCase()
  if (!q) return branches.value
  return branches.value.filter((b) => b.toLowerCase().includes(q))
})

async function pick(branch: string, close: () => void) {
  if (branch === current.value) {
    reset()
    close()
    return
  }
  const ok = await checkout(branch, false)
  if (ok) {
    reset()
    close()
  }
  // On failure keep the panel open: either an error message or — when git refused
  // a dirty-tree switch — the confirmation dialog stays visible.
}

// Retry a blocked switch with the chosen strategy (stash keeps changes, force
// discards them). Closes the panel on success.
async function applyStrategy(strategy: 'stash' | 'force', close: () => void) {
  const ok = await resolvePending(strategy)
  if (ok) {
    reset()
    close()
  }
}

function startCreate() {
  creating.value = true
  newName.value = query.value.trim()
  nextTick(() => newInput.value?.focus())
}

async function confirmCreate(close: () => void) {
  const name = newName.value.trim()
  if (!name) return
  const ok = await checkout(name, true)
  if (ok) {
    reset()
    close()
  }
}

function reset() {
  query.value = ''
  creating.value = false
  newName.value = ''
  error.value = ''
  cancelPending()
}
</script>

<template>
  <!-- Only shown for git workspaces (no current branch ⇒ not a repo). -->
  <div v-if="current" class="bp-bar">
    <Popover class="bp-popover" style="position: relative">
      <PopoverButton as="template" :disabled="switching">
        <button
          class="bp-pill"
          :disabled="switching"
          :title="t('branches.current', { name: current })"
          @click="reset"
        >
          <CodeBracketIcon class="w-3 h-3 bp-pill-icon" />
          <span class="bp-name">{{ current }}</span>
          <ChevronDownIcon class="w-3 h-3 bp-caret" />
        </button>
      </PopoverButton>

      <transition
        enter-active-class="pop-enter-active"
        enter-from-class="pop-enter-from"
        leave-active-class="pop-leave-active"
        leave-to-class="pop-leave-to"
      >
        <PopoverPanel
          v-slot="{ close }"
          class="bp-panel"
          :class="placement === 'top' ? 'place-top' : 'place-bottom'"
        >
          <!-- Confirmation: git refused to switch because it would overwrite
               uncommitted work. Offer to stash (safe) or discard (force). -->
          <div v-if="pending" class="bp-confirm">
            <div class="bp-confirm-title">{{ t('branches.confirmTitle') }}</div>
            <div class="bp-confirm-intro">
              {{ t('branches.confirmIntro', { branch: pending.branch }) }}
            </div>
            <ul v-if="pending.files.length" class="bp-confirm-files">
              <li v-for="f in pending.files.slice(0, MAX_FILES)" :key="f">{{ f }}</li>
              <li v-if="pending.files.length > MAX_FILES" class="bp-confirm-more">
                {{ t('branches.confirmMore', { count: pending.files.length - MAX_FILES }) }}
              </li>
            </ul>

            <div v-if="error" class="bp-error">{{ error }}</div>

            <div class="bp-confirm-actions">
              <button class="bp-confirm-btn stash" :disabled="switching" @click="applyStrategy('stash', close)">
                {{ t('branches.confirmStash') }}
              </button>
              <button class="bp-confirm-btn discard" :disabled="switching" @click="applyStrategy('force', close)">
                {{ t('branches.confirmDiscard') }}
              </button>
              <button class="bp-confirm-btn cancel" :disabled="switching" @click="reset">
                {{ t('branches.confirmCancel') }}
              </button>
            </div>
            <div class="bp-confirm-hint">{{ t('branches.confirmHint') }}</div>
          </div>

          <template v-else>
            <div class="bp-search">
              <MagnifyingGlassIcon class="w-3 h-3 bp-search-icon" />
              <input v-model="query" class="bp-search-input" :placeholder="t('branches.search')" />
            </div>

            <div class="bp-section">{{ t('branches.title') }}</div>
            <div class="bp-list">
              <div v-if="filtered.length === 0" class="bp-hint">{{ t('branches.none') }}</div>
              <button
                v-for="b in filtered"
                :key="b"
                class="bp-row"
                :class="{ active: b === current }"
                :disabled="switching"
                @click="pick(b, close)"
              >
                <CodeBracketIcon class="w-3 h-3 bp-row-icon" />
                <span class="bp-row-name">{{ b }}</span>
                <CheckIcon v-if="b === current" class="w-3.5 h-3.5 bp-check" />
              </button>
            </div>

            <div v-if="error" class="bp-error">{{ error }}</div>

            <div class="bp-actions">
              <button v-if="!creating" class="bp-action" @click="startCreate">
                <PlusIcon class="w-3.5 h-3.5" /> <span>{{ t('branches.create') }}</span>
              </button>
              <div v-else class="bp-create">
                <input
                  ref="newInput"
                  v-model="newName"
                  class="bp-create-input"
                  :placeholder="t('branches.newName')"
                  @keydown.enter="confirmCreate(close)"
                  @keydown.esc="creating = false"
                />
                <button
                  class="bp-create-btn"
                  :disabled="!newName.trim() || switching"
                  @click="confirmCreate(close)"
                >
                  {{ t('branches.createBtn') }}
                </button>
              </div>
            </div>
          </template>
        </PopoverPanel>
      </transition>
    </Popover>
  </div>
</template>

<style scoped>
.bp-bar {
  display: inline-flex;
  align-items: center;
  min-width: 0;
}
.bp-popover {
  display: inline-flex;
  min-width: 0;
}

.bp-pill {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  height: 28px;
  max-width: 200px;
  padding: 0 8px;
  border: 1px solid transparent;
  border-radius: var(--radius-lg);
  background: transparent;
  color: var(--color-muted-foreground);
  cursor: pointer;
  transition: background 0.15s, transform 0.06s ease;
}
.bp-pill:hover:not(:disabled) {
  background: var(--color-muted);
}
.bp-pill:active:not(:disabled) {
  transform: translateY(0.5px);
}
.bp-pill:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}
.bp-pill-icon {
  flex-shrink: 0;
}
.bp-name {
  font-family: var(--font-mono);
  font-size: 11.5px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.bp-caret {
  flex-shrink: 0;
  margin-left: 1px;
  opacity: 0.7;
}

.bp-panel {
  position: absolute;
  left: 0;
  z-index: 40;
  width: 300px;
  max-width: 84vw;
  padding: 6px;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-xl);
  box-shadow: var(--shadow-lg);
}
.bp-panel.place-top {
  bottom: calc(100% + 6px);
}
.bp-panel.place-bottom {
  top: calc(100% + 6px);
}

.bp-search {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 5px 8px;
  margin-bottom: 4px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  background: var(--color-background);
}
.bp-search-icon {
  color: var(--color-muted-foreground);
  flex-shrink: 0;
}
.bp-search-input {
  flex: 1;
  min-width: 0;
  border: none;
  outline: none;
  background: transparent;
  font-size: 12.5px;
  color: var(--color-foreground);
}
.bp-search-input::placeholder {
  color: var(--color-muted-foreground);
}

.bp-section {
  padding: 4px 8px 2px;
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--color-muted-foreground);
}

.bp-list {
  max-height: 240px;
  overflow-y: auto;
  padding: 2px;
}
.bp-row {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  padding: 7px 8px;
  border: none;
  background: transparent;
  border-radius: var(--radius-md);
  cursor: pointer;
  text-align: left;
  color: var(--color-foreground);
  font-size: 12.5px;
  font-family: var(--font-mono);
  transition: background 0.12s;
}
.bp-row:hover:not(:disabled) {
  background: var(--color-muted);
}
.bp-row.active {
  background: var(--neutral-wash-soft);
}
.bp-row:disabled {
  opacity: 0.6;
  cursor: default;
}
.bp-row-icon {
  color: var(--color-muted-foreground);
  flex-shrink: 0;
}
.bp-row.active .bp-row-icon {
  color: var(--color-accent-neutral);
}
.bp-row-name {
  flex: 1;
  min-width: 0;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.bp-check {
  color: var(--color-accent-neutral);
  flex-shrink: 0;
}
.bp-hint {
  padding: 14px 8px;
  text-align: center;
  font-size: 11.5px;
  color: var(--color-muted-foreground);
}

.bp-error {
  margin: 4px 2px 2px;
  padding: 7px 9px;
  border-radius: var(--radius-md);
  background: var(--color-error-bg);
  color: var(--color-error-fg);
  font-size: 11.5px;
  line-height: 1.45;
  white-space: pre-wrap;
  word-break: break-word;
}

.bp-confirm {
  padding: 6px 6px 4px;
}
.bp-confirm-title {
  font-size: 12.5px;
  font-weight: 600;
  color: var(--color-foreground);
}
.bp-confirm-intro {
  margin-top: 4px;
  font-size: 11.5px;
  line-height: 1.45;
  color: var(--color-muted-foreground);
}
.bp-confirm-files {
  margin: 8px 0 2px;
  padding: 6px 8px;
  max-height: 132px;
  overflow-y: auto;
  list-style: none;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  background: var(--color-background);
}
.bp-confirm-files li {
  font-family: var(--font-mono);
  font-size: 11px;
  line-height: 1.6;
  color: var(--color-foreground);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.bp-confirm-files .bp-confirm-more {
  font-family: inherit;
  color: var(--color-muted-foreground);
}
.bp-confirm-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-top: 10px;
}
.bp-confirm-btn {
  flex: 1 1 auto;
  height: 30px;
  padding: 0 10px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  background: var(--color-surface);
  color: var(--color-foreground);
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.12s, opacity 0.15s;
}
.bp-confirm-btn:hover:not(:disabled) {
  background: var(--color-muted);
}
.bp-confirm-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.bp-confirm-btn.stash {
  border-color: transparent;
  background: var(--color-accent-neutral);
  color: var(--color-surface);
}
.bp-confirm-btn.stash:hover:not(:disabled) {
  background: var(--color-accent-neutral);
  opacity: 0.9;
}
.bp-confirm-btn.discard {
  border-color: var(--color-error-fg);
  color: var(--color-error-fg);
}
.bp-confirm-btn.discard:hover:not(:disabled) {
  background: var(--color-error-bg);
}
.bp-confirm-hint {
  margin-top: 8px;
  font-size: 10.5px;
  line-height: 1.45;
  color: var(--color-muted-foreground);
}

.bp-actions {
  margin-top: 4px;
  padding-top: 4px;
  border-top: 1px solid var(--color-border);
}
.bp-action {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  padding: 8px;
  border: none;
  background: transparent;
  border-radius: var(--radius-md);
  cursor: pointer;
  font-size: 12.5px;
  color: var(--color-foreground);
  transition: background 0.12s;
}
.bp-action:hover {
  background: var(--color-muted);
}
.bp-action svg {
  color: var(--color-muted-foreground);
  flex-shrink: 0;
}

.bp-create {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 4px;
}
.bp-create-input {
  flex: 1;
  min-width: 0;
  height: 30px;
  padding: 0 9px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  background: var(--color-background);
  color: var(--color-foreground);
  font-family: var(--font-mono);
  font-size: 12px;
  outline: none;
}
.bp-create-input:focus {
  border-color: var(--color-accent-neutral);
}
.bp-create-btn {
  flex-shrink: 0;
  height: 30px;
  padding: 0 12px;
  border: none;
  border-radius: var(--radius-md);
  background: var(--color-accent-neutral);
  color: var(--color-surface);
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
  transition: opacity 0.15s;
}
.bp-create-btn:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.pop-enter-active,
.pop-leave-active {
  transition: opacity 0.12s ease, transform 0.12s ease;
}
.pop-enter-from,
.pop-leave-to {
  opacity: 0;
  transform: translateY(4px);
}
.bp-panel.place-bottom.pop-enter-from,
.bp-panel.place-bottom.pop-leave-to {
  transform: translateY(-4px);
}
</style>
