// web-react/src/components/ChannelsView.tsx
/**
 * ChannelsView — external messaging channels (WeChat).
 *
 * Faithful port of web/src/components/ChannelsView.vue. Two-column stage:
 *   LEFT  — a brand-tinted promo card (eyebrow, title, lede, three features,
 *           connect CTA). While scanning it shows the WeChat login QR; while
 *           connected it shows a status row + disconnect button.
 *   RIGHT — a static, purely-decorative phone mockup showing a fake WeChat
 *           conversation (approval card + done summary pill). No logic.
 *
 * No BLE here (BLE lives in SettingsDialog). The QR flow mirrors the Vue
 * original: login → render QR → poll channel status every 2s (capped at 3m)
 * → detect scan → online → logout. The view owns its own scan lifecycle.
 *
 * Strings are ported from web/src/i18n/locales/en.ts (channels.* + the
 * settings.channels.* keys the Vue file reuses); the React app has no i18n.
 */

import { useCallback, useEffect, useRef, useState } from 'react'
import {
  SignalIcon,
  CursorArrowRaysIcon,
  BellAlertIcon,
  QrCodeIcon,
  DevicePhoneMobileIcon,
  CheckBadgeIcon,
} from '@heroicons/react/24/outline'
import QRCode from 'qrcode'
import { api } from '../lib/api'

// Finer-grained string the QR flow drives.
type ChannelState = 'none' | 'scanning' | 'enabled' | 'disabled'

interface Feature {
  icon: typeof SignalIcon
  title: string
  desc: string
}

const FEATURES: Feature[] = [
  {
    icon: CursorArrowRaysIcon,
    title: 'One-tap approvals',
    desc: 'Approve or deny a tool call right from the WeChat message — no need to open the app.',
  },
  {
    icon: BellAlertIcon,
    title: 'Done notifications',
    desc: 'Get pinged the moment a scheduled automation or background task finishes.',
  },
  {
    icon: QrCodeIcon,
    title: 'Scan to connect',
    desc: 'Pair in seconds with a QR code. Disconnect any time from Settings → Channels.',
  },
]

export function ChannelsView() {
  // ── WeChat channel state ──
  const [channelAvailable, setChannelAvailable] = useState(false)
  const [channelState, setChannelState] = useState<ChannelState>('none')
  const [channelLoading, setChannelLoading] = useState(false)
  const [qrDataUrl, setQrDataUrl] = useState('')
  const [loginReminder, setLoginReminder] = useState(false)

  // Polling handles, on refs so teardown and a fresh poll share the same slots.
  const pollIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const pollTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const fetchStatus = useCallback(async () => {
    try {
      const ch = await api.channelStatus()
      setChannelAvailable(ch.available)
      setChannelState((ch.state as ChannelState) || 'none')
    } catch {
      /* ignore */
    }
  }, [])

  // Initial load.
  useEffect(() => {
    void fetchStatus()
  }, [fetchStatus])

  const stopPoll = useCallback(() => {
    if (pollIntervalRef.current) {
      clearInterval(pollIntervalRef.current)
      pollIntervalRef.current = null
    }
    if (pollTimeoutRef.current) {
      clearTimeout(pollTimeoutRef.current)
      pollTimeoutRef.current = null
    }
  }, [])

  // Tear down the poll on unmount.
  useEffect(() => stopPoll, [stopPoll])

  // Poll channel status every 2s while a QR is pending, to detect when the user
  // has scanned it. Safety-capped at 3 minutes regardless of outcome.
  const pollChannelState = useCallback(
    (previousState: ChannelState) => {
      stopPoll()
      pollIntervalRef.current = setInterval(async () => {
        try {
          const ch = await api.channelStatus()
          if (ch.state === 'enabled' || ch.state === 'disabled') {
            const next = ch.state as ChannelState
            setChannelState(next)
            setQrDataUrl('')
            setChannelAvailable(true)
            // Show the "activate" reminder the first time we go online via the
            // login flow (scanning → enabled).
            if (next === 'enabled' && previousState === 'scanning') {
              setLoginReminder(true)
            }
            stopPoll()
          }
        } catch {
          /* keep polling */
        }
      }, 2000)
      pollTimeoutRef.current = setTimeout(stopPoll, 180000)
    },
    [stopPoll],
  )

  const channelLogin = useCallback(async () => {
    setChannelLoading(true)
    try {
      const result = await api.channelLogin()
      // Render the QR as a data URL (img src). Colors resolve at call time so a
      // theme switch mid-scan re-renders cleanly.
      const fg =
        getComputedStyle(document.documentElement).getPropertyValue('--color-foreground').trim() ||
        '#18181b'
      const bg =
        getComputedStyle(document.documentElement).getPropertyValue('--color-surface').trim() ||
        '#ffffff'
      const url = await QRCode.toDataURL(result.qr_content, {
        width: 200,
        margin: 2,
        color: { dark: fg, light: bg },
      })
      setQrDataUrl(url)
      setChannelState('scanning')
      pollChannelState('scanning')
    } catch (err) {
      console.error('Channel login failed:', err)
    }
    setChannelLoading(false)
  }, [pollChannelState])

  const channelLogout = useCallback(async () => {
    setChannelLoading(true)
    try {
      await api.channelLogout()
      setChannelState('none')
      setQrDataUrl('')
      setChannelAvailable(false)
      setLoginReminder(false)
    } catch (err) {
      console.error('Channel logout failed:', err)
    }
    setChannelLoading(false)
  }, [])

  const isConnected = channelState === 'enabled'
  const isScanning = channelState === 'scanning'

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <header className="flex h-[var(--header-height)] shrink-0 items-center gap-2 border-b border-[var(--color-border)] bg-[var(--color-surface)] px-4">
        <SignalIcon className="h-4 w-4 text-[var(--color-primary)]" />
        <h1 className="text-sm font-medium">Channels</h1>
      </header>

      <div className="min-h-0 flex-1 overflow-y-auto">
        <div className="mx-auto w-full max-w-[56rem] px-5 pb-8">
          {/* Two-column stage: promo card (left) + phone mock (right). Stacks
              below 860px, mirroring the Vue media query. */}
          <div className="chan-stage">
            {/* ── LEFT: promo / connection card ── */}
            <div className="promo-card">
              <div className="promo-glow" aria-hidden />
              <div className="promo-inner">
                <span className="promo-eyebrow">
                  <SignalIcon className="h-3.5 w-3.5" />
                  Channels
                </span>
                <h2 className="promo-title">
                  Approve and monitor from <span className="accent">your phone</span>
                </h2>
                <p className="promo-lede">
                  Link WeChat once. jcode forwards every approval request and task-completion notice
                  straight to your chat — so a long-running agent never waits on you being at the
                  desk.
                </p>

                {/* Connect flow: QR while scanning */}
                {isScanning && (
                  <div className="qr-block">
                    {qrDataUrl && (
                      /* eslint-disable-next-line @next/next/no-img-element -- local data URL */
                      <img
                        src={qrDataUrl}
                        alt="WeChat login QR code"
                        className="qr-canvas"
                        width={200}
                        height={200}
                      />
                    )}
                    <p className="qr-hint">Scan with WeChat to connect</p>
                  </div>
                )}

                {/* Connected state */}
                {!isScanning && isConnected && (
                  <div className="connected">
                    <div className="conn-status">
                      <span className="conn-dot" />
                      <span>Connected</span>
                    </div>
                    {loginReminder && (
                      <p className="conn-reminder">
                        Please send any message to the WeChat bot now to activate notifications.
                        Once activated, you can receive notifications for 24 hours.
                      </p>
                    )}
                    <button
                      type="button"
                      onClick={channelLogout}
                      disabled={channelLoading}
                      className="btn-outline"
                    >
                      Disconnect
                    </button>
                  </div>
                )}

                {/* Feature list + CTA (disconnected) */}
                {!isScanning && !isConnected && (
                  <>
                    <div className="promo-features">
                      {FEATURES.map((f) => {
                        const Icon = f.icon
                        return (
                          <div key={f.title} className="promo-feat">
                            <span className="feat-ic">
                              <Icon className="h-4 w-4" />
                            </span>
                            <div>
                              <h4>{f.title}</h4>
                              <p>{f.desc}</p>
                            </div>
                          </div>
                        )
                      })}
                    </div>

                    <div className="promo-cta">
                      <button
                        type="button"
                        onClick={channelLogin}
                        disabled={channelLoading}
                        className="btn-primary"
                      >
                        <DevicePhoneMobileIcon className="h-4 w-4" />
                        {channelLoading ? 'Loading…' : 'Connect'}
                      </button>
                      {!channelAvailable && <span className="cta-hint">No channels configured</span>}
                    </div>
                  </>
                )}
              </div>
            </div>

            {/* ── RIGHT: phone mock — what the remote experience looks like.
                  Static decorative HTML/CSS, no logic. Ported verbatim from
                  the Vue template. ── */}
            <div className="phone-col">
              <div className="phone">
                <div className="phone-notch" />
                <div className="phone-screen">
                  <div className="phone-status">
                    <span>9:41</span>
                    <span className="bat" />
                  </div>

                  <div className="wc-msg">
                    <div className="wc-head">
                      <span className="wc-avatar">j</span>
                      <span className="wc-name">jcode</span>
                      <span className="wc-time">now</span>
                    </div>
                    <div className="wc-body">
                      <b>Approval needed</b>
                      <br />
                      <span className="muted">Run</span> <code>git push origin</code>{' '}
                      <span className="muted">?</span>
                    </div>
                    <div className="wc-actions">
                      <button type="button" className="wc-btn approve">
                        Approve
                      </button>
                      <button type="button" className="wc-btn deny">
                        Deny
                      </button>
                    </div>
                  </div>

                  <div className="wc-msg-2">
                    <div className="wc-sub">jcode · now</div>
                    <div className="wc-line">✓ Nightly automations finished</div>
                    <span className="wc-pill">
                      <CheckBadgeIcon className="h-2.5 w-2.5" /> 3 tasks · 0 failed
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Component-local styles ── Ports the Vue <style scoped> block.
            Tailwind v4 @layer prevents these from being purged and keeps them
            low-specificity so utilities can still override. */}
      <style>{`
.chan-stage { display: flex; gap: 40px; align-items: flex-start; padding-top: 16px; }
@media (max-width: 860px) { .chan-stage { flex-direction: column; } }

/* ── Promo card (left-anchored) ── */
.promo-card {
  flex: 1;
  min-width: 0;
  position: relative;
  background:
    radial-gradient(120% 80% at 0% 0%, color-mix(in srgb, var(--color-primary) 8%, transparent), transparent 60%),
    var(--color-background);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-2xl);
  overflow: hidden;
}
.promo-glow {
  position: absolute;
  top: -90px; left: -60px;
  width: 280px; height: 280px;
  border-radius: 50%;
  background: color-mix(in srgb, var(--color-primary) 13%, transparent);
  filter: blur(46px);
  opacity: 0.8;
  pointer-events: none;
}
.promo-inner { position: relative; padding: 32px; display: flex; flex-direction: column; }
.promo-eyebrow {
  align-self: flex-start;
  display: inline-flex;
  align-items: center;
  gap: 7px;
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: var(--color-primary);
  padding: 5px 11px;
  border-radius: var(--radius-pill);
  background: color-mix(in srgb, var(--color-primary) 8%, transparent);
  border: 1px solid color-mix(in srgb, var(--color-primary) 35%, transparent);
}
.promo-title {
  font-size: 26px;
  font-weight: 600;
  letter-spacing: -0.02em;
  margin: 18px 0 0;
  line-height: 1.15;
}
.promo-title .accent { color: var(--color-primary); }
.promo-lede {
  font-size: 13.5px;
  color: var(--color-muted-foreground);
  line-height: 1.6;
  margin: 14px 0 0;
  max-width: 44ch;
}

.promo-features { display: flex; flex-direction: column; gap: 16px; margin: 24px 0 0; }
.promo-feat { display: flex; gap: 13px; align-items: flex-start; }
.feat-ic {
  display: grid; place-items: center;
  width: 36px; height: 36px; flex-shrink: 0;
  border-radius: var(--radius-lg);
  background: color-mix(in srgb, var(--color-foreground) 8%, transparent);
  border: 1px solid color-mix(in srgb, var(--color-foreground) 30%, transparent);
  color: var(--color-foreground);
}
.promo-feat h4 { font-size: 13.5px; font-weight: 600; margin: 3px 0 3px; }
.promo-feat p { font-size: 12.5px; color: var(--color-muted-foreground); line-height: 1.5; margin: 0; max-width: 42ch; }

.promo-cta { display: flex; align-items: center; gap: 14px; margin-top: 26px; flex-wrap: wrap; }
.btn-primary {
  display: inline-flex; align-items: center; gap: 8px;
  padding: 10px 18px;
  background: var(--color-primary);
  color: var(--color-on-primary, #fff);
  border: none;
  border-radius: var(--radius-pill);
  font-size: 13px;
  font-weight: 600;
  cursor: pointer;
  box-shadow: 0 4px 16px -4px color-mix(in srgb, var(--color-primary) 60%, transparent);
  transition: box-shadow 0.15s, opacity 0.15s;
}
.btn-primary:hover:not(:disabled) { box-shadow: 0 6px 22px -5px color-mix(in srgb, var(--color-primary) 70%, transparent); }
.btn-primary:disabled { opacity: 0.6; cursor: not-allowed; }
.cta-hint { font-size: 11.5px; color: var(--color-muted-foreground); }

/* ── Connect (QR) ── */
.qr-block { display: flex; flex-direction: column; align-items: center; gap: 10px; margin-top: 22px; }
.qr-canvas { border: 1px solid var(--color-border); border-radius: var(--radius-md); }
.qr-hint { font-size: 12px; color: var(--color-muted-foreground); }

/* ── Connected ── */
.connected { margin-top: 22px; display: flex; flex-direction: column; gap: 14px; }
.conn-status { display: inline-flex; align-items: center; gap: 8px; font-size: 13.5px; font-weight: 600; color: var(--color-success); }
.conn-dot { width: 8px; height: 8px; border-radius: var(--radius-pill); background: var(--color-success); }
.conn-reminder {
  font-size: 12px; line-height: 1.5; color: var(--color-foreground);
  background: color-mix(in srgb, var(--color-primary) 10%, transparent);
  border: 1px solid color-mix(in srgb, var(--color-primary) 30%, transparent);
  border-radius: var(--radius-lg); padding: 10px 12px;
  margin: 0;
}
.btn-outline {
  align-self: flex-start;
  padding: 7px 14px;
  font-size: 12.5px;
  font-weight: 500;
  border-radius: var(--radius-lg);
  border: 1px solid var(--color-border);
  background: var(--color-surface);
  color: var(--color-foreground);
  cursor: pointer;
  transition: background 0.15s;
}
.btn-outline:hover:not(:disabled) { background: var(--color-muted); }
.btn-outline:disabled { opacity: 0.6; cursor: not-allowed; }

/* ── Phone mock (right) ── */
.phone-col { flex: 0 0 auto; display: flex; padding-top: 24px; }
.phone {
  width: 240px;
  border: 2px solid var(--color-foreground);
  border-radius: 32px;
  padding: 10px;
  background: var(--color-background);
  box-shadow: var(--shadow-xl);
  position: relative;
}
.phone-notch {
  position: absolute; top: 10px; left: 50%; transform: translateX(-50%);
  width: 72px; height: 18px;
  background: var(--color-foreground);
  border-radius: 0 0 12px 12px;
}
.phone-screen {
  border-radius: 24px;
  overflow: hidden;
  background: var(--color-muted);
  height: 400px;
  padding: 32px 12px 14px;
  display: flex;
  flex-direction: column;
  gap: 11px;
}
.phone-status { display: flex; align-items: center; justify-content: space-between; font-size: 9px; color: var(--color-muted-foreground); padding: 0 6px; }
.bat { width: 16px; height: 8px; border: 1px solid currentColor; border-radius: 2px; position: relative; }
.bat::after { content: ''; position: absolute; inset: 1px; background: currentColor; border-radius: 1px; }

.wc-msg, .wc-msg-2 { background: var(--color-surface); border: 1px solid var(--color-border); border-radius: 12px; }
.wc-msg { padding: 12px 13px; box-shadow: var(--shadow-sm); }
.wc-head { display: flex; align-items: center; gap: 7px; margin-bottom: 8px; }
.wc-avatar { width: 22px; height: 22px; border-radius: 6px; background: var(--color-primary); display: grid; place-items: center; color: #fff; font-size: 10px; font-weight: 700; font-family: var(--font-mono); }
.wc-name { font-size: 11.5px; font-weight: 600; }
.wc-time { margin-left: auto; font-size: 9px; color: var(--color-muted-foreground); }
.wc-body { font-size: 11.5px; line-height: 1.5; color: var(--color-foreground); }
.wc-body .muted { color: var(--color-muted-foreground); }
.wc-body code { font-family: var(--font-mono); font-size: 10px; background: var(--color-muted); padding: 1px 4px; border-radius: 3px; }
.wc-actions { display: flex; gap: 8px; margin-top: 10px; }
.wc-btn { flex: 1; padding: 8px 0; border-radius: 8px; font-size: 11px; font-weight: 600; border: none; cursor: default; }
.wc-btn.approve { background: #07C160; color: #fff; }
.wc-btn.deny { background: var(--color-muted); color: var(--color-foreground); border: 1px solid var(--color-border); }
.wc-msg-2 { padding: 10px 13px; }
.wc-sub { font-size: 10px; color: var(--color-muted-foreground); margin-bottom: 3px; }
.wc-line { font-size: 11.5px; font-weight: 500; }
.wc-pill { display: inline-flex; align-items: center; gap: 4px; font-size: 10px; font-weight: 600; color: #07C160; background: color-mix(in srgb, #07C160 12%, transparent); padding: 2px 8px; border-radius: var(--radius-pill); margin-top: 7px; }
`}</style>
    </div>
  )
}

// web/src/components/ChannelsView.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, nextTick, watch } from 'vue'
import {
  SignalIcon,
  CursorArrowRaysIcon,
  BellAlertIcon,
  QrCodeIcon,
  DevicePhoneMobileIcon,
  CheckBadgeIcon,
} from '@heroicons/vue/24/outline'
import QRCode from 'qrcode'
import { useI18n } from 'vue-i18n'
import { useChatStore } from '@/stores/chat'
import { api } from '@/composables/api'
import PageSurface from '@/components/PageSurface.vue'

// Channels is a page inside the shell (same inset-surface geometry as
// AutomationsView via the shared PageSurface), not an overlay. The parent
// (<main> in App.vue) mounts this via v-if, so the channel-status fetch fires
// on entry and the poll tears down on exit. The WeChat login/QR/poll logic
// mirrors SettingsDialog's Channels tab (kept local on purpose — a shared
// composable was deferred to avoid touching SettingsDialog).
const { t } = useI18n()
const store = useChatStore()

// Channel state. `channelState` is the finer-grained string the QR flow needs;
// store.channelEnabled is the derived boolean the rest of the app reads.
const channelAvailable = ref(false)
const channelState = ref<'none' | 'scanning' | 'enabled' | 'disabled'>('none')
const channelLoading = ref(false)
const channelQRContent = ref('')
const channelLoginReminder = ref(false)
const qrCanvas = ref<HTMLCanvasElement | null>(null)

async function fetchStatus() {
  try {
    const ch = await api.channelStatus()
    channelAvailable.value = ch.available
    channelState.value = (ch.state as typeof channelState.value) || 'none'
    store.channelEnabled = ch.state === 'enabled'
  } catch { /* ignore */ }
}

onMounted(() => { void fetchStatus() })

// ── WeChat connect (QR) ── mirrored from SettingsDialog so this page owns its
// own scan lifecycle without depending on the settings dialog being open.
async function drawChannelQR() {
  await nextTick()
  if (!qrCanvas.value || !channelQRContent.value) return
  // Resolve QR colors from design tokens so the code follows the active theme.
  const root = document.documentElement
  const fg = getComputedStyle(root).getPropertyValue('--term-fg').trim() || '#18181b'
  const bg = getComputedStyle(root).getPropertyValue('--color-surface').trim() || '#ffffff'
  await QRCode.toCanvas(qrCanvas.value, channelQRContent.value, {
    width: 200,
    margin: 2,
    color: { dark: fg, light: bg },
  })
}

async function channelLogin() {
  channelLoading.value = true
  try {
    const result = await api.channelLogin()
    channelQRContent.value = result.qr_content
    channelState.value = 'scanning'
    await drawChannelQR()
    pollChannelState()
  } catch (err) {
    console.error('Channel login failed:', err)
  }
  channelLoading.value = false
}

async function channelLogout() {
  channelLoading.value = true
  try {
    await api.channelLogout()
    channelState.value = 'none'
    channelQRContent.value = ''
    store.channelEnabled = false
    channelAvailable.value = false
  } catch (err) {
    console.error('Channel logout failed:', err)
  }
  channelLoading.value = false
}

let channelPollInterval: ReturnType<typeof setInterval> | null = null
let channelPollTimeout: ReturnType<typeof setTimeout> | null = null

function stopChannelPoll() {
  if (channelPollInterval) { clearInterval(channelPollInterval); channelPollInterval = null }
  if (channelPollTimeout) { clearTimeout(channelPollTimeout); channelPollTimeout = null }
}

function pollChannelState() {
  stopChannelPoll()
  const previousState = channelState.value
  channelPollInterval = setInterval(async () => {
    try {
      const ch = await api.channelStatus()
      if (ch.state === 'enabled' || ch.state === 'disabled') {
        channelState.value = ch.state as typeof channelState.value
        channelQRContent.value = ''
        channelAvailable.value = true
        store.channelEnabled = ch.state === 'enabled'
        if (ch.state === 'enabled' && previousState === 'scanning') {
          channelLoginReminder.value = true
        }
        stopChannelPoll()
      }
    } catch { /* ignore */ }
  }, 2000)
  channelPollTimeout = setTimeout(stopChannelPoll, 180000)
}

onUnmounted(() => { stopChannelPoll() })

const isConnected = computed(() => channelState.value === 'enabled')
const isScanning = computed(() => channelState.value === 'scanning')

// Re-draw the QR if it's mid-scan and the canvas remounts (e.g. after a theme
// switch re-evaluates the v-if). Mirrors the settings tab re-entry behavior.
watch(channelQRContent, (v) => { if (v) void drawChannelQR() })

const features = computed(() => [
  { icon: CursorArrowRaysIcon, title: t('channels.features.approvals.title'), desc: t('channels.features.approvals.desc') },
  { icon: BellAlertIcon, title: t('channels.features.notifications.title'), desc: t('channels.features.notifications.desc') },
  { icon: QrCodeIcon, title: t('channels.features.scan.title'), desc: t('channels.features.scan.desc') },
])
</script>

<template>
  <PageSurface :title="t('nav.channels')">
      <div class="chan-stage">
        <!-- LEFT: promo / connection card -->
        <div class="promo-card">
          <div class="promo-glow" aria-hidden="true" />
          <div class="promo-inner">
            <span class="promo-eyebrow">
              <SignalIcon class="w-3.5 h-3.5" /> {{ t('nav.channels') }}
            </span>
            <h2 class="promo-title" v-html="t('channels.promo.title')" />
            <p class="promo-lede">{{ t('channels.promo.lede') }}</p>

            <!-- Connect flow: QR while scanning -->
            <div v-if="isScanning" class="qr-block">
              <canvas ref="qrCanvas" class="qr-canvas" />
              <p class="qr-hint">{{ t('settings.channels.scanQr') }}</p>
            </div>

            <!-- Connected state -->
            <div v-else-if="isConnected" class="connected">
              <div class="conn-status">
                <span class="conn-dot" />
                <span>{{ t('channels.connected') }}</span>
              </div>
              <p v-if="channelLoginReminder" class="conn-reminder">{{ t('settings.channels.activateBody') }}</p>
              <button class="btn-outline" :disabled="channelLoading" @click="channelLogout">
                {{ t('settings.channels.disconnect') }}
              </button>
            </div>

            <!-- Feature list + CTA (disconnected) -->
            <template v-else>
              <div class="promo-features">
                <div v-for="f in features" :key="f.title" class="promo-feat">
                  <span class="feat-ic"><component :is="f.icon" class="w-4 h-4" /></span>
                  <div>
                    <h4>{{ f.title }}</h4>
                    <p>{{ f.desc }}</p>
                  </div>
                </div>
              </div>

              <div class="promo-cta">
                <button class="btn-primary" :disabled="channelLoading" @click="channelLogin">
                  <DevicePhoneMobileIcon class="w-4 h-4" />
                  {{ channelLoading ? t('settings.channels.loadingHint') : t('settings.channels.connect') }}
                </button>
                <span v-if="!channelAvailable" class="cta-hint">{{ t('settings.channels.noneConfigured') }}</span>
              </div>
            </template>
          </div>
        </div>

        <!-- RIGHT: phone mock — what the remote experience looks like -->
        <div class="phone-col">
          <div class="phone">
            <div class="phone-notch" />
            <div class="phone-screen">
              <div class="phone-status"><span>9:41</span><span class="bat" /></div>

              <div class="wc-msg">
                <div class="wc-head">
                  <span class="wc-avatar">j</span>
                  <span class="wc-name">jcode</span>
                  <span class="wc-time">{{ t('channels.mock.now') }}</span>
                </div>
                <div class="wc-body">
                  <b>{{ t('channels.mock.approvalTitle') }}</b><br>
                  <span class="muted">{{ t('channels.mock.run') }}</span>
                  <code>git push origin</code>
                  <span class="muted">?</span>
                </div>
                <div class="wc-actions">
                  <button class="wc-btn approve">{{ t('channels.mock.approve') }}</button>
                  <button class="wc-btn deny">{{ t('channels.mock.deny') }}</button>
                </div>
              </div>

              <div class="wc-msg-2">
                <div class="wc-sub">jcode · {{ t('channels.mock.now') }}</div>
                <div class="wc-line">✓ {{ t('channels.mock.done') }}</div>
                <span class="wc-pill">
                  <CheckBadgeIcon class="w-2.5 h-2.5" /> {{ t('channels.mock.summary') }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
  </PageSurface>
</template>

<style scoped>
/* The page surface (inset chrome + title head + scroll body) is owned by
 * PageSurface. This component styles only its own content. Content column is
 * centered + inset to match the chat timeline, scoped to PageSurface's body. */
:deep(.page-body) > * { max-width: 56rem; margin-left: auto; margin-right: auto; padding: 0 20px 32px; }

.chan-stage { display: flex; gap: 40px; align-items: flex-start; padding-top: 16px; }
@media (max-width: 860px) { .chan-stage { flex-direction: column; } }

/* ── Promo card (left-anchored) ── */
.promo-card {
  flex: 1;
  min-width: 0;
  position: relative;
  background:
    radial-gradient(120% 80% at 0% 0%, color-mix(in srgb, var(--color-primary) 8%, transparent), transparent 60%),
    var(--color-background);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-2xl);
  overflow: hidden;
}
.promo-glow {
  position: absolute;
  top: -90px; left: -60px;
  width: 280px; height: 280px;
  border-radius: 50%;
  background: color-mix(in srgb, var(--color-primary) 13%, transparent);
  filter: blur(46px);
  opacity: 0.8;
  pointer-events: none;
}
.promo-inner { position: relative; padding: 32px; display: flex; flex-direction: column; }
.promo-eyebrow {
  align-self: flex-start;
  display: inline-flex;
  align-items: center;
  gap: 7px;
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: var(--color-primary);
  padding: 5px 11px;
  border-radius: var(--radius-pill);
  background: color-mix(in srgb, var(--color-primary) 8%, transparent);
  border: 1px solid color-mix(in srgb, var(--color-primary) 35%, transparent);
}
.promo-title {
  font-size: 26px;
  font-weight: 600;
  letter-spacing: -0.02em;
  margin: 18px 0 0;
  line-height: 1.15;
}
.promo-title :deep(.accent) { color: var(--color-primary); }
.promo-lede {
  font-size: 13.5px;
  color: var(--color-muted-foreground);
  line-height: 1.6;
  margin: 14px 0 0;
  max-width: 44ch;
}

.promo-features { display: flex; flex-direction: column; gap: 16px; margin: 24px 0 0; }
.promo-feat { display: flex; gap: 13px; align-items: flex-start; }
.feat-ic {
  display: grid; place-items: center;
  width: 36px; height: 36px; flex-shrink: 0;
  border-radius: var(--radius-lg);
  background: color-mix(in srgb, var(--color-foreground) 8%, transparent);
  border: 1px solid color-mix(in srgb, var(--color-foreground) 30%, transparent);
  color: var(--color-foreground);
}
.promo-feat h4 { font-size: 13.5px; font-weight: 600; margin: 3px 0 3px; }
.promo-feat p { font-size: 12.5px; color: var(--color-muted-foreground); line-height: 1.5; margin: 0; max-width: 42ch; }

.promo-cta { display: flex; align-items: center; gap: 14px; margin-top: 26px; flex-wrap: wrap; }
.btn-primary {
  display: inline-flex; align-items: center; gap: 8px;
  padding: 10px 18px;
  background: var(--color-primary);
  color: var(--color-on-primary, #fff);
  border: none;
  border-radius: var(--radius-pill);
  font-size: 13px;
  font-weight: 600;
  cursor: pointer;
  box-shadow: 0 4px 16px -4px color-mix(in srgb, var(--color-primary) 60%, transparent);
  transition: box-shadow 0.15s, opacity 0.15s;
}
.btn-primary:hover:not(:disabled) { box-shadow: 0 6px 22px -5px color-mix(in srgb, var(--color-primary) 70%, transparent); }
.btn-primary:disabled { opacity: 0.6; cursor: not-allowed; }
.cta-hint { font-size: 11.5px; color: var(--color-muted-foreground); }

/* ── Connect (QR) ── */
.qr-block { display: flex; flex-direction: column; align-items: center; gap: 10px; margin-top: 22px; }
.qr-canvas { border: 1px solid var(--color-border); border-radius: var(--radius-md); }
.qr-hint { font-size: 12px; color: var(--color-muted-foreground); }

/* ── Connected ── */
.connected { margin-top: 22px; display: flex; flex-direction: column; gap: 14px; }
.conn-status { display: inline-flex; align-items: center; gap: 8px; font-size: 13.5px; font-weight: 600; color: var(--color-success); }
.conn-dot { width: 8px; height: 8px; border-radius: var(--radius-pill); background: var(--color-success); }
.conn-reminder {
  font-size: 12px; line-height: 1.5; color: var(--color-foreground);
  background: color-mix(in srgb, var(--color-primary) 10%, transparent);
  border: 1px solid color-mix(in srgb, var(--color-primary) 30%, transparent);
  border-radius: var(--radius-lg); padding: 10px 12px;
}
.btn-outline {
  align-self: flex-start;
  padding: 7px 14px;
  font-size: 12.5px;
  font-weight: 500;
  border-radius: var(--radius-lg);
  border: 1px solid var(--color-border);
  background: var(--color-surface);
  color: var(--color-foreground);
  cursor: pointer;
  transition: background 0.15s;
}
.btn-outline:hover:not(:disabled) { background: var(--color-muted); }
.btn-outline:disabled { opacity: 0.6; cursor: not-allowed; }

/* ── Phone mock (right) ── */
.phone-col { flex: 0 0 auto; display: flex; padding-top: 24px; }
.phone {
  width: 240px;
  border: 2px solid var(--color-foreground);
  border-radius: 32px;
  padding: 10px;
  background: var(--color-background);
  box-shadow: var(--shadow-xl);
  position: relative;
}
.phone-notch {
  position: absolute; top: 10px; left: 50%; transform: translateX(-50%);
  width: 72px; height: 18px;
  background: var(--color-foreground);
  border-radius: 0 0 12px 12px;
}
.phone-screen {
  border-radius: 24px;
  overflow: hidden;
  background: var(--color-muted);
  height: 400px;
  padding: 32px 12px 14px;
  display: flex;
  flex-direction: column;
  gap: 11px;
}
.phone-status { display: flex; align-items: center; justify-content: space-between; font-size: 9px; color: var(--color-muted-foreground); padding: 0 6px; }
.bat { width: 16px; height: 8px; border: 1px solid currentColor; border-radius: 2px; position: relative; }
.bat::after { content: ''; position: absolute; inset: 1px; background: currentColor; border-radius: 1px; }

.wc-msg, .wc-msg-2 { background: var(--color-surface); border: 1px solid var(--color-border); border-radius: 12px; }
.wc-msg { padding: 12px 13px; box-shadow: var(--shadow-sm); }
.wc-head { display: flex; align-items: center; gap: 7px; margin-bottom: 8px; }
.wc-avatar { width: 22px; height: 22px; border-radius: 6px; background: var(--color-primary); display: grid; place-items: center; color: #fff; font-size: 10px; font-weight: 700; font-family: var(--font-mono); }
.wc-name { font-size: 11.5px; font-weight: 600; }
.wc-time { margin-left: auto; font-size: 9px; color: var(--color-muted-foreground); }
.wc-body { font-size: 11.5px; line-height: 1.5; color: var(--color-foreground); }
.wc-body .muted { color: var(--color-muted-foreground); }
.wc-body code { font-family: var(--font-mono); font-size: 10px; background: var(--color-muted); padding: 1px 4px; border-radius: 3px; }
.wc-actions { display: flex; gap: 8px; margin-top: 10px; }
.wc-btn { flex: 1; padding: 8px 0; border-radius: 8px; font-size: 11px; font-weight: 600; border: none; cursor: default; }
.wc-btn.approve { background: #07C160; color: #fff; }
.wc-btn.deny { background: var(--color-muted); color: var(--color-foreground); border: 1px solid var(--color-border); }
.wc-msg-2 { padding: 10px 13px; }
.wc-sub { font-size: 10px; color: var(--color-muted-foreground); margin-bottom: 3px; }
.wc-line { font-size: 11.5px; font-weight: 500; }
.wc-pill { display: inline-flex; align-items: center; gap: 4px; font-size: 10px; font-weight: 600; color: #07C160; background: color-mix(in srgb, #07C160 12%, transparent); padding: 2px 8px; border-radius: var(--radius-pill); margin-top: 7px; }
</style>
