// web-react/src/components/Sidebar.tsx
/**
 * Sidebar — chat/session list + nav (chat / automations / channels).
 *
 * A closer port of the Vue Sidebar: the session list is enriched with task
 * metadata (pinned/archived/unread/running/updated_at) so it can be filtered
 * (status / time window / sort), grouped by recency (Today / Yesterday /
 * This Week / Older), and acted on via a right-click context menu
 * (Pin / Archive / Mark read / Delete) backed by `api.updateTask`.
 *
 * Kept from the prior React version: the nav buttons, the "New chat" button,
 * the footer (ThemeToggle + settings), and the `loadSession` thunk on click.
 */

import { useEffect, useMemo, useRef, useState } from 'react'
import {
  PlusIcon,
  ChatBubbleLeftIcon,
  BoltIcon,
  ChatBubbleOvalLeftIcon,
  Cog6ToothIcon,
  AdjustmentsHorizontalIcon,
  BookmarkIcon,
  ArchiveBoxIcon,
  ArchiveBoxArrowDownIcon,
  EnvelopeOpenIcon,
  TrashIcon,
  CheckIcon,
  EllipsisHorizontalIcon,
} from '@heroicons/react/24/outline'
import { useAppDispatch, useAppSelector } from '../app/hooks'
import { uiActions, sessionActions, chatActions, loadSession } from '../app/store'
import { api } from '../lib/api'
import type { SessionItem, TaskItem } from '../lib/types'
import { ThemeToggle } from './ThemeToggle'

// ─── Filter state (local; mirrors SidebarFilterMenu.vue's options) ───

type StatusFilter = 'all' | 'active' | 'archived'
type TimeFilter = 'all' | 'today' | 'week' | 'month'
type SortFilter = 'recent' | 'title'

interface FilterState {
  status: StatusFilter
  time: TimeFilter
  sort: SortFilter
}

const DEFAULT_FILTERS: FilterState = { status: 'all', time: 'all', sort: 'recent' }

const STATUS_OPTIONS: { value: StatusFilter; label: string }[] = [
  { value: 'all', label: 'All' },
  { value: 'active', label: 'Active' },
  { value: 'archived', label: 'Archived' },
]
const TIME_OPTIONS: { value: TimeFilter; label: string }[] = [
  { value: 'all', label: 'All time' },
  { value: 'today', label: 'Today' },
  { value: 'week', label: 'This week' },
  { value: 'month', label: 'This month' },
]
const SORT_OPTIONS: { value: SortFilter; label: string }[] = [
  { value: 'recent', label: 'Recent' },
  { value: 'title', label: 'Title' },
]

// ─── Enriched row: a session joined with its task metadata ───

interface SessionRow {
  uuid: string
  title: string
  created_at: string
  updated_at: string
  pinned: boolean
  archived: boolean
  unread: boolean
  running: boolean
}

interface DateGroup {
  key: string
  label: string
  items: SessionRow[]
}

const DAY = 86400000

export function Sidebar() {
  const dispatch = useAppDispatch()
  const sessions = useAppSelector((s) => s.session.sessions)
  const tasks = useAppSelector((s) => s.session.tasks)
  const currentSessionId = useAppSelector((s) => s.session.currentSessionId)
  const activeView = useAppSelector((s) => s.ui.activeView)

  // Filters live in local state (the Vue app keeps them in the project store;
  // here they're component-local, which is enough for a single sidebar).
  const [filters, setFilters] = useState<FilterState>(DEFAULT_FILTERS)
  const [filterOpen, setFilterOpen] = useState(false)
  const filterRef = useRef<HTMLDivElement | null>(null)

  // Right-click / ⋯ context menu.
  const [ctx, setCtx] = useState<{ x: number; y: number; row: SessionRow } | null>(null)
  const ctxRef = useRef<HTMLDivElement | null>(null)

  // A coarse clock so time-based filtering/grouping re-evaluates as the wall
  // clock advances (Date.now() isn't a reactive dep on its own).
  const [now, setNow] = useState(() => Date.now())
  useEffect(() => {
    const t = setInterval(() => setNow(Date.now()), 60000)
    return () => clearInterval(t)
  }, [])

  // Join sessions with task metadata by uuid. Sessions are the current-project
  // conversation list (guaranteed correct scope); tasks carry the pin/archive/
  // unread/running/updated_at fields the filter + context menu need.
  const taskMap = useMemo(() => new Map(tasks.map((t) => [t.uuid, t])), [tasks])
  const rows = useMemo<SessionRow[]>(() => {
    return sessions.map((s: SessionItem) => {
      const t: TaskItem | undefined = taskMap.get(s.uuid)
      return {
        uuid: s.uuid,
        title: s.title || t?.title || '',
        created_at: s.created_at || t?.created_at || '',
        updated_at: t?.updated_at || s.created_at || t?.created_at || '',
        pinned: t?.pinned ?? false,
        archived: t?.archived ?? false,
        unread: t?.unread ?? false,
        running: t?.running ?? false,
      }
    })
  }, [sessions, taskMap])

  // ── Filter pipeline ──

  const filtered = useMemo(() => {
    return rows.filter((r) => {
      // The open conversation always stays visible regardless of filters —
      // otherwise archiving or a narrowing window would strand it.
      if (r.uuid === currentSessionId) return true
      if (filters.status === 'active' && r.archived) return false
      if (filters.status === 'archived' && !r.archived) return false
      if (filters.time !== 'all') {
        const ts = r.updated_at || r.created_at || ''
        const then = new Date(ts).getTime()
        if (Number.isNaN(then)) return false
        const span = filters.time === 'today' ? DAY : filters.time === 'week' ? 7 * DAY : 30 * DAY
        if (now - then > span) return false
      }
      return true
    })
  }, [rows, filters, currentSessionId, now])

  // ── Sort: running first, then pinned, then the chosen key ──

  const sorted = useMemo(() => {
    const arr = [...filtered]
    arr.sort((a, b) => {
      if (a.running !== b.running) return a.running ? -1 : 1
      if (a.pinned !== b.pinned) return a.pinned ? -1 : 1
      if (filters.sort === 'title') return rowTitle(a).localeCompare(rowTitle(b))
      return (b.updated_at || '').localeCompare(a.updated_at || '')
    })
    return arr
  }, [filtered, filters.sort])

  // ── Group by recency (calendar-day based for today/yesterday) ──

  const groups = useMemo<DateGroup[]>(() => {
    const map = new Map<string, SessionRow[]>()
    for (const r of sorted) {
      const key = bucketFor(r.updated_at || r.created_at || '', now)
      const arr = map.get(key)
      if (arr) arr.push(r)
      else map.set(key, [r])
    }
    return BUCKET_ORDER.filter((k) => map.has(k)).map((k) => ({
      key: k,
      label: BUCKET_LABEL[k],
      items: map.get(k)!,
    }))
  }, [sorted, now])

  // ── Outside-click / Esc handling for the filter + context menus ──

  useEffect(() => {
    if (!filterOpen) return
    function onDown(e: MouseEvent) {
      if (filterRef.current && !filterRef.current.contains(e.target as Node)) setFilterOpen(false)
    }
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') setFilterOpen(false)
    }
    document.addEventListener('mousedown', onDown)
    document.addEventListener('keydown', onKey)
    return () => {
      document.removeEventListener('mousedown', onDown)
      document.removeEventListener('keydown', onKey)
    }
  }, [filterOpen])

  useEffect(() => {
    if (!ctx) return
    function onDown(e: MouseEvent) {
      if (ctxRef.current && !ctxRef.current.contains(e.target as Node)) setCtx(null)
    }
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') setCtx(null)
    }
    document.addEventListener('mousedown', onDown)
    document.addEventListener('keydown', onKey)
    window.addEventListener('blur', onKey as never)
    return () => {
      document.removeEventListener('mousedown', onDown)
      document.removeEventListener('keydown', onKey)
      window.removeEventListener('blur', onKey as never)
    }
  }, [ctx])

  const isDirty =
    filters.status !== DEFAULT_FILTERS.status ||
    filters.time !== DEFAULT_FILTERS.time ||
    filters.sort !== DEFAULT_FILTERS.sort

  // ── Actions ──

  async function newChat() {
    dispatch(chatActions.clearChat())
    dispatch(sessionActions.setCurrentSession(''))
    dispatch(uiActions.setView('chat'))
    try {
      const resp = await api.newSession()
      dispatch(sessionActions.setCurrentSession(resp.session_id))
      const fresh = await api.sessions()
      dispatch(sessionActions.setSessions(fresh))
    } catch {
      // surfaced via health/gate
    }
  }

  async function openItem(row: SessionRow) {
    dispatch(uiActions.setView('chat'))
    if (row.unread) await patchTask(row.uuid, { unread: false })
    await dispatch(loadSession(row.uuid))
  }

  // Apply a task metadata patch via the API and merge the result into the
  // store's task list so the UI reflects it immediately.
  async function patchTask(uuid: string, patch: Parameters<typeof api.updateTask>[1]) {
    try {
      const updated = await api.updateTask(uuid, patch)
      const next = tasks.map((t) => (t.uuid === uuid ? updated : t))
      dispatch(sessionActions.setTasks(next))
    } catch {
      // ignore — the next tasks refresh will reconcile
    }
  }

  async function deleteItem(row: SessionRow) {
    const wasActive = row.uuid === currentSessionId
    try {
      await api.deleteSession(row.uuid)
    } catch {
      return
    }
    dispatch(sessionActions.setSessions(sessions.filter((s) => s.uuid !== row.uuid)))
    dispatch(sessionActions.setTasks(tasks.filter((t) => t.uuid !== row.uuid)))
    if (wasActive) {
      dispatch(chatActions.clearChat())
      dispatch(sessionActions.setCurrentSession(''))
      dispatch(chatActions.setRunning(false))
    }
  }

  function openContext(e: React.MouseEvent, row: SessionRow) {
    e.preventDefault()
    e.stopPropagation()
    // Clamp so the menu never overflows the viewport.
    const x = Math.min(e.clientX, window.innerWidth - 180)
    const y = Math.min(e.clientY, window.innerHeight - 200)
    setCtx({ x, y, row })
  }

  function openContextFromButton(e: React.MouseEvent, row: SessionRow) {
    e.preventDefault()
    e.stopPropagation()
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect()
    const x = Math.min(rect.left, window.innerWidth - 180)
    // Flip up if there's no room below.
    const below = rect.bottom + 210 > window.innerHeight
    const y = below ? Math.max(8, rect.top - 200) : rect.bottom + 4
    setCtx({ x, y, row })
  }

  function setFilter<K extends keyof FilterState>(key: K, value: FilterState[K]) {
    setFilters((f) => ({ ...f, [key]: value }))
  }

  const ctxRow = ctx?.row

  return (
    <aside className="flex w-[var(--sidebar-width)] shrink-0 flex-col border-r border-[var(--color-border)] bg-[var(--color-sidebar-bg)]">
      {/* New chat */}
      <div className="p-2">
        <button
          type="button"
          onClick={newChat}
          className="sb-newchat flex w-full items-center gap-2 rounded-[var(--radius-lg)] bg-[var(--color-primary)] px-3 py-2 text-sm font-medium text-[var(--color-on-primary)] hover:bg-[var(--accent-wash-strong)]"
        >
          <PlusIcon className="h-4 w-4" />
          New chat
        </button>
      </div>

      {/* View nav */}
      <nav className="px-2 pb-1">
        <NavItem icon={ChatBubbleLeftIcon} label="Chat" active={activeView === 'chat'} onClick={() => dispatch(uiActions.setView('chat'))} />
        <NavItem icon={BoltIcon} label="Automations" active={activeView === 'automations'} onClick={() => dispatch(uiActions.setView('automations'))} />
        <NavItem icon={ChatBubbleOvalLeftIcon} label="Channels" active={activeView === 'channels'} onClick={() => dispatch(uiActions.setView('channels'))} />
      </nav>

      {/* Chat heading + filter menu */}
      <div className="flex items-center justify-between px-3 pb-1 pt-2">
        <span className="text-[0.65rem] font-semibold uppercase tracking-[0.06em] text-[var(--color-muted-foreground)]">
          Chat
        </span>
        <div ref={filterRef} className="relative inline-flex">
          <button
            type="button"
            onClick={() => setFilterOpen((v) => !v)}
            title="Filter conversations"
            aria-label="Filter conversations"
            aria-expanded={filterOpen}
            className={`relative grid h-[22px] w-[22px] place-items-center rounded-[var(--radius-sm)] text-[var(--color-muted-foreground)] transition-colors hover:bg-[var(--color-muted)] hover:text-[var(--color-foreground)] ${
              filterOpen || isDirty ? 'text-[var(--color-foreground)]' : ''
            } ${filterOpen ? 'bg-[var(--color-muted)]' : ''}`}
          >
            <AdjustmentsHorizontalIcon className="h-4 w-4" />
            {isDirty && (
              <span className="absolute right-[1px] top-[1px] h-[5px] w-[5px] rounded-full bg-[var(--color-accent-neutral)]" aria-hidden="true" />
            )}
          </button>
          {filterOpen && (
            <div
              className="sb-pop absolute right-0 top-full z-[var(--z-dropdown)] mt-1 w-[232px] rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-1 shadow-[var(--shadow-md)]"
              role="menu"
            >
              <FilterSection label="Status" options={STATUS_OPTIONS} value={filters.status} onSelect={(v) => setFilter('status', v)} />
              <div className="my-1 h-px bg-[var(--color-border)]" />
              <FilterSection label="Time" options={TIME_OPTIONS} value={filters.time} onSelect={(v) => setFilter('time', v)} />
              <div className="my-1 h-px bg-[var(--color-border)]" />
              <FilterSection label="Sort" options={SORT_OPTIONS} value={filters.sort} onSelect={(v) => setFilter('sort', v)} />
              {isDirty && (
                <>
                  <div className="my-1 h-px bg-[var(--color-border)]" />
                  <button
                    type="button"
                    onClick={() => setFilters(DEFAULT_FILTERS)}
                    className="flex w-full items-center gap-2 rounded-[var(--radius-md)] px-2 py-1.5 text-left text-[12.5px] text-[var(--color-muted-foreground)] transition-colors hover:bg-[var(--color-muted)]"
                  >
                    Reset
                  </button>
                </>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Session list, grouped by recency */}
      <div className="min-h-0 flex-1 overflow-y-auto px-1 pb-2">
        {groups.length === 0 ? (
          <div className="px-3 py-6 text-center text-xs text-[var(--color-muted-foreground)]">No conversations yet</div>
        ) : (
          groups.map((g) => (
            <div key={g.key} className="mb-0.5">
              <div className="flex items-center gap-1.5 px-2 pb-1 pt-2">
                <span className="flex-1 text-[0.65rem] font-semibold uppercase tracking-[0.06em] text-[var(--color-muted-foreground)]">{g.label}</span>
                <span className="font-mono text-[0.625rem] text-[var(--color-muted-foreground)]">{g.items.length}</span>
              </div>
              {g.items.map((row) => {
                const active = row.uuid === currentSessionId
                return (
                  <div
                    key={row.uuid}
                    role="button"
                    tabIndex={0}
                    onClick={() => openItem(row)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' || e.key === ' ') {
                        e.preventDefault()
                        openItem(row)
                      }
                    }}
                    onContextMenu={(e) => openContext(e, row)}
                    className={`sb-row group flex w-full cursor-pointer items-center gap-2 rounded-[var(--radius-md)] border-l border-transparent px-2.5 py-1.5 text-left text-sm transition-colors ${
                      active
                        ? 'border-l-[var(--color-accent-neutral)] bg-[var(--accent-wash)] text-[var(--color-foreground)]'
                        : row.archived
                          ? 'text-[var(--color-muted-foreground)] hover:bg-[var(--neutral-wash-soft)]'
                          : 'text-[var(--color-foreground)] hover:bg-[var(--neutral-wash-soft)]'
                    } ${row.running ? 'border-l-[color-mix(in_srgb,var(--color-accent)_50%,transparent)]' : ''}`}
                  >
                    {row.running ? (
                      <span className="sb-ring h-[11px] w-[11px] shrink-0 rounded-full border-[1.6px] border-[var(--color-accent)]" aria-hidden="true" />
                    ) : (
                      <span
                        className={`h-[6px] w-[6px] shrink-0 rounded-full ${row.unread ? 'bg-[var(--color-accent-neutral)]' : 'bg-transparent'}`}
                        aria-hidden="true"
                      />
                    )}
                    {row.pinned && <BookmarkIcon className="h-2.5 w-2.5 shrink-0 text-[var(--color-accent-neutral)]" />}
                    <span className="min-w-0 flex-1 truncate">{rowTitle(row)}</span>
                    <span className={`shrink-0 font-mono text-[0.625rem] ${row.running ? 'text-[var(--color-accent)]' : 'text-[var(--color-muted-foreground)]'}`}>
                      {row.running ? 'running' : relativeTime(row.updated_at || row.created_at, now)}
                    </span>
                    <button
                      type="button"
                      title="Actions"
                      aria-label="Actions"
                      onClick={(e) => openContextFromButton(e, row)}
                      className="grid h-5 w-5 shrink-0 place-items-center rounded-[var(--radius-sm)] text-[var(--color-muted-foreground)] opacity-0 transition-all hover:bg-[var(--color-secondary)] hover:text-[var(--color-foreground)] group-hover:opacity-100"
                    >
                      <EllipsisHorizontalIcon className="h-3.5 w-3.5" />
                    </button>
                  </div>
                )
              })}
            </div>
          ))
        )}
      </div>

      {/* Footer: theme toggle + settings (matches Vue sidebar footer) */}
      <div className="flex shrink-0 items-center justify-end gap-1 px-3 py-2">
        <ThemeToggle compact />
        <button
          type="button"
          onClick={() => dispatch(uiActions.setSettingsOpen(true))}
          className="rounded-[var(--radius-md)] p-1.5 text-[var(--color-muted-foreground)] transition-colors hover:bg-[var(--neutral-wash-soft)] hover:text-[var(--color-foreground)]"
          aria-label="Settings"
          title="Settings (⌘,)"
        >
          <Cog6ToothIcon className="h-3.5 w-3.5" />
        </button>
      </div>

      {/* Right-click / ⋯ context menu (fixed-positioned at the cursor) */}
      {ctx && ctxRow && (
        <div
          ref={ctxRef}
          role="menu"
          className="sb-pop fixed z-[var(--z-dropdown)] min-w-[170px] rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-1 shadow-[var(--shadow-md)]"
          style={{ left: ctx.x, top: ctx.y }}
        >
          <CtxItem icon={BookmarkIcon} label={ctxRow.pinned ? 'Unpin' : 'Pin'} onClick={() => { void patchTask(ctxRow.uuid, { pinned: !ctxRow.pinned }); setCtx(null) }} />
          <CtxItem
            icon={ctxRow.archived ? ArchiveBoxArrowDownIcon : ArchiveBoxIcon}
            label={ctxRow.archived ? 'Unarchive' : 'Archive'}
            onClick={() => { void patchTask(ctxRow.uuid, { archived: !ctxRow.archived }); setCtx(null) }}
          />
          <CtxItem icon={EnvelopeOpenIcon} label={ctxRow.unread ? 'Mark read' : 'Mark unread'} onClick={() => { void patchTask(ctxRow.uuid, { unread: !ctxRow.unread }); setCtx(null) }} />
          <div className="my-1 h-px bg-[var(--color-border)]" />
          <CtxItem icon={TrashIcon} label="Delete" danger onClick={() => { void deleteItem(ctxRow); setCtx(null) }} />
        </div>
      )}

      {/* Animations: running ring breathe + pop-in for menus. Scoped via sb-* names. */}
      <style>{`
        @keyframes sb-ring-breathe { 0%,100% { opacity:0.35; transform:scale(0.78); } 50% { opacity:1; transform:scale(1); } }
        @keyframes sb-pop-in { from { opacity:0; transform:translateY(-4px); } to { opacity:1; transform:none; } }
        .sb-ring { animation: sb-ring-breathe 1.6s ease-in-out infinite; }
        .sb-pop { animation: sb-pop-in 0.12s ease; }
        .sb-newchat { transition: background 0.15s, transform 0.1s; }
        .sb-newchat:active { transform: scale(0.98); }
        .sb-row { transition: background 0.15s, border-color 0.15s; }
        @media (prefers-reduced-motion: reduce) {
          .sb-ring { animation: none; opacity: 1; transform: none; }
          .sb-pop { animation: none; }
        }
      `}</style>
    </aside>
  )
}

// ─── Sub-components ───

function FilterSection<T extends string>({
  label,
  options,
  value,
  onSelect,
}: {
  label: string
  options: { value: T; label: string }[]
  value: T
  onSelect: (v: T) => void
}) {
  return (
    <div>
      <div className="px-2 py-1 text-[0.625rem] font-semibold uppercase tracking-wide text-[var(--color-muted-foreground)]">{label}</div>
      {options.map((o) => {
        const selected = o.value === value
        return (
          <button
            key={o.value}
            type="button"
            onClick={() => onSelect(o.value)}
            className={`flex w-full items-center gap-2 rounded-[var(--radius-md)] px-2 py-1.5 text-left text-[12.5px] transition-colors hover:bg-[var(--color-muted)] ${
              selected ? 'text-[var(--color-accent-neutral)]' : 'text-[var(--color-foreground)]'
            }`}
          >
            <span className="flex-1 truncate">{o.label}</span>
            {selected && <CheckIcon className="h-3.5 w-3.5 shrink-0 text-[var(--color-accent-neutral)]" />}
          </button>
        )
      })}
    </div>
  )
}

function CtxItem({
  icon: Icon,
  label,
  onClick,
  danger,
}: {
  icon: React.ComponentType<{ className?: string }>
  label: string
  onClick: () => void
  danger?: boolean
}) {
  return (
    <button
      type="button"
      role="menuitem"
      onClick={onClick}
      className={`flex w-full items-center gap-2 rounded-[var(--radius-md)] px-2 py-1.5 text-left text-[12.5px] transition-colors hover:bg-[var(--color-muted)] ${
        danger ? 'text-[var(--color-destructive)]' : 'text-[var(--color-foreground)]'
      }`}
    >
      <Icon className="h-3.5 w-3.5" />
      {label}
    </button>
  )
}

function NavItem({
  icon: Icon,
  label,
  active,
  onClick,
}: {
  icon: React.ComponentType<{ className?: string }>
  label: string
  active: boolean
  onClick: () => void
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`flex w-full items-center gap-2 rounded-[var(--radius-md)] px-2.5 py-1.5 text-sm transition-colors ${
        active
          ? 'bg-[var(--accent-wash)] font-medium text-[var(--color-foreground)]'
          : 'text-[var(--color-foreground)] hover:bg-[var(--neutral-wash-soft)]'
      }`}
    >
      <Icon className="h-4 w-4" />
      {label}
    </button>
  )
}

// ─── Helpers ───

function rowTitle(r: SessionRow): string {
  return r.title || r.uuid.slice(0, 8) + '…'
}

const BUCKET_ORDER = ['today', 'yesterday', 'week', 'older'] as const
const BUCKET_LABEL: Record<(typeof BUCKET_ORDER)[number], string> = {
  today: 'Today',
  yesterday: 'Yesterday',
  week: 'This Week',
  older: 'Older',
}

function bucketFor(ts: string, now: number): (typeof BUCKET_ORDER)[number] {
  const then = new Date(ts).getTime()
  if (Number.isNaN(then)) return 'older'
  const today = new Date(now)
  const startToday = new Date(today.getFullYear(), today.getMonth(), today.getDate()).getTime()
  if (then >= startToday) return 'today'
  if (then >= startToday - DAY) return 'yesterday'
  if (then >= startToday - 7 * DAY) return 'week'
  return 'older'
}

function relativeTime(ts: string, now: number): string {
  if (!ts) return ''
  const then = new Date(ts).getTime()
  if (Number.isNaN(then)) return ''
  const mins = Math.floor((now - then) / 60000)
  if (mins < 1) return 'now'
  if (mins < 60) return `${mins}m`
  const hrs = Math.floor(mins / 60)
  if (hrs < 24) return `${hrs}h`
  const days = Math.floor(hrs / 24)
  if (days < 30) return `${days}d`
  return new Date(ts).toLocaleDateString([], { month: 'short', day: 'numeric' })
}

// web/src/components/Sidebar.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
import { ref, computed, onMounted, watch, inject } from 'vue'
import {
  Menu as HMenu,
  MenuButton,
  MenuItems,
  MenuItem,
} from '@headlessui/vue'
import {
  ChevronRight,
  Folder,
  FolderOpen,
  Server,
  Plus,
  MoreHorizontal,
  Pin,
  Archive,
  ArchiveRestore,
  Pencil,
  Trash2,
  MailOpen,
} from 'lucide-vue-next'
import { useChatStore } from '@/stores/chat'
import { useProjectStore, isRemotePath, parseRemoteLabel } from '@/stores/project'
import type { TaskItem, RemoteMeta } from '@/types/api'

const store = useChatStore()
const projectStore = useProjectStore()
const openRemoteConnect = inject<(prefill?: RemoteMeta & { loadTaskUuid?: string }) => void>('openRemoteConnect')

defineProps<{
  resolvedTheme: 'light' | 'dark'
}>()

const emit = defineEmits<{
  openFile: [path: string, content: string]
  openSettings: []
  openProjects: []
  toggleTheme: []
}>()

// Expanded project paths. The active project is auto-expanded.
const expanded = ref<Set<string>>(new Set())
const showArchived = ref(false)

// The task "⋯" menu opens downward by default; for rows near the bottom of the
// sidebar that clips it, so flip it upward when there isn't room below.
const flipUpMenus = ref<Set<string>>(new Set())
function onTaskMenuClick(e: MouseEvent, uuid: string) {
  const rect = (e.currentTarget as HTMLElement).getBoundingClientRect()
  const next = new Set(flipUpMenus.value)
  if (rect.bottom + 200 > window.innerHeight - 12) next.add(uuid)
  else next.delete(uuid)
  flipUpMenus.value = next
}

const activePath = computed(() => projectStore.activeProject?.path || store.pwd)

function isExpanded(path: string): boolean {
  return expanded.value.has(path)
}
function toggle(path: string) {
  const next = new Set(expanded.value)
  if (next.has(path)) next.delete(path)
  else next.add(path)
  expanded.value = next
}

// Project nodes sorted with the active project first, then alphabetically.
const projectNodes = computed(() => {
  const nodes = [...projectStore.projectsForTree]
  return nodes.sort((a, b) => {
    if (a.path === activePath.value) return -1
    if (b.path === activePath.value) return 1
    return a.name.localeCompare(b.name)
  })
})

function tasksFor(path: string): TaskItem[] {
  const list = projectStore.tasksByProject[path] || []
  return showArchived.value ? list : list.filter((t) => !t.archived)
}

function visibleCount(path: string): number {
  return tasksFor(path).length
}

async function refresh() {
  await projectStore.fetchAllTasks()
}

onMounted(() => {
  refresh()
  if (activePath.value) expanded.value = new Set([activePath.value])
})

// Keep the active project expanded and the tree fresh as the active session /
// session list changes (new task, send, delete).
watch(activePath, (p) => {
  if (p && !expanded.value.has(p)) toggle(p)
})
watch(() => store.sessions.length, refresh)
watch(() => store.currentSessionId, refresh)

async function openTask(task: TaskItem) {
  if (task.unread) projectStore.updateTaskMeta(task.uuid, { unread: false })

  // Remote tasks: if their workspace is already the active connection just load
  // the transcript; otherwise reconnect via the SSH wizard (it loads the task
  // after binding). We never persist the SSH secret, so a fresh connect is
  // required to continue the conversation.
  if (isRemotePath(task.project)) {
    if (activePath.value === task.project) {
      await store.loadSession(task.uuid)
    } else {
      const meta = parseRemoteLabel(task.project)
      if (meta) openRemoteConnect?.({ ...meta, loadTaskUuid: task.uuid })
    }
    return
  }

  if (activePath.value !== task.project) {
    const ok = await projectStore.openProject(task.project)
    if (!ok) return
    await store.fetchHealth()
  }
  await store.loadSession(task.uuid)
}

function projIcon(path: string) {
  if (isRemotePath(path)) return Server
  return path === activePath.value ? FolderOpen : Folder
}

function isActiveTask(task: TaskItem): boolean {
  return task.uuid === store.currentSessionId && activePath.value === task.project
}

async function handleDelete(task: TaskItem) {
  await store.deleteSession(task.uuid)
  await refresh()
}

async function renameTask(task: TaskItem) {
  const title = window.prompt('Rename task', task.title || '')
  if (title != null && title.trim()) {
    await projectStore.updateTaskMeta(task.uuid, { title: title.trim() })
  }
}

function taskTitle(t: TaskItem): string {
  return t.title || t.uuid.slice(0, 8) + '…'
}

function relativeTime(ts: string): string {
  if (!ts) return ''
  const then = new Date(ts).getTime()
  if (Number.isNaN(then)) return ''
  const mins = Math.floor((Date.now() - then) / 60000)
  if (mins < 1) return 'now'
  if (mins < 60) return `${mins}m`
  const hrs = Math.floor(mins / 60)
  if (hrs < 24) return `${hrs}h`
  const days = Math.floor(hrs / 24)
  if (days < 30) return `${days}d`
  return new Date(ts).toLocaleDateString([], { month: 'short', day: 'numeric' })
}
</script>

<template>
  <aside class="sidebar">
    <!-- New task -->
    <div class="sidebar-header">
      <button class="new-task-btn" @click="store.newSession()">
        <Plus :size="16" />
        <span>New task</span>
      </button>
    </div>

    <!-- Workspace tree -->
    <div class="tree">
      <div class="tree-head">
        <span class="tree-label">Workspace</span>
      </div>

      <div v-if="projectNodes.length === 0" class="empty-state">No projects yet</div>

      <div v-for="proj in projectNodes" :key="proj.path" class="project-group">
        <button class="project-row" :class="{ active: proj.path === activePath }" @click="toggle(proj.path)">
          <ChevronRight :size="14" class="proj-chevron" :class="{ open: isExpanded(proj.path) }" />
          <component :is="projIcon(proj.path)" :size="15" class="proj-icon" />
          <span class="proj-name">{{ proj.name }}</span>
          <span v-if="visibleCount(proj.path) > 0" class="proj-count">{{ visibleCount(proj.path) }}</span>
        </button>

        <div v-show="isExpanded(proj.path)" class="task-list">
          <div v-if="visibleCount(proj.path) === 0" class="task-empty">No tasks</div>
          <div
            v-for="task in tasksFor(proj.path)"
            :key="task.uuid"
            class="task-row"
            :class="{ active: isActiveTask(task), archived: task.archived }"
            @click="openTask(task)"
          >
            <span class="task-dot" :class="{ unread: task.unread }" aria-hidden="true" />
            <Pin v-if="task.pinned" :size="11" class="task-pin" />
            <span class="task-title">{{ taskTitle(task) }}</span>
            <span class="task-time">{{ relativeTime(task.created_at) }}</span>

            <HMenu as="div" class="task-menu" @click.stop>
              <MenuButton class="task-menu-btn" title="Task actions" @click.stop="onTaskMenuClick($event, task.uuid)">
                <MoreHorizontal :size="14" />
              </MenuButton>
              <transition
                enter-active-class="pop-enter-active"
                enter-from-class="pop-enter-from"
                leave-active-class="pop-leave-active"
                leave-to-class="pop-leave-to"
              >
                <MenuItems class="task-menu-items" :class="{ 'flip-up': flipUpMenus.has(task.uuid) }">
                  <MenuItem v-slot="{ active }">
                    <button class="tmi" :class="{ hl: active }" @click.stop="projectStore.updateTaskMeta(task.uuid, { pinned: !task.pinned })">
                      <Pin :size="14" /> {{ task.pinned ? 'Unpin' : 'Pin' }}
                    </button>
                  </MenuItem>
                  <MenuItem v-slot="{ active }">
                    <button class="tmi" :class="{ hl: active }" @click.stop="renameTask(task)">
                      <Pencil :size="14" /> Rename
                    </button>
                  </MenuItem>
                  <MenuItem v-slot="{ active }">
                    <button class="tmi" :class="{ hl: active }" @click.stop="projectStore.updateTaskMeta(task.uuid, { archived: !task.archived })">
                      <component :is="task.archived ? ArchiveRestore : Archive" :size="14" /> {{ task.archived ? 'Unarchive' : 'Archive' }}
                    </button>
                  </MenuItem>
                  <MenuItem v-slot="{ active }">
                    <button class="tmi" :class="{ hl: active }" @click.stop="projectStore.updateTaskMeta(task.uuid, { unread: !task.unread })">
                      <MailOpen :size="14" /> {{ task.unread ? 'Mark read' : 'Mark unread' }}
                    </button>
                  </MenuItem>
                  <div class="tmi-sep" />
                  <MenuItem v-slot="{ active }">
                    <button class="tmi danger" :class="{ hl: active }" @click.stop="handleDelete(task)">
                      <Trash2 :size="14" /> Delete
                    </button>
                  </MenuItem>
                </MenuItems>
              </transition>
            </HMenu>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <div class="sidebar-footer">
      <div class="footer-actions">
        <button class="footer-btn" @click="emit('toggleTheme')" :title="resolvedTheme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'">
          <svg v-if="resolvedTheme === 'dark'" class="w-3.5 h-3.5" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10 2a.75.75 0 01.75.75v1.5a.75.75 0 01-1.5 0v-1.5A.75.75 0 0110 2zM10 15a.75.75 0 01.75.75v1.5a.75.75 0 01-1.5 0v-1.5A.75.75 0 0110 15zM10 7a3 3 0 100 6 3 3 0 000-6zM15.657 5.404a.75.75 0 10-1.06-1.06l-1.061 1.06a.75.75 0 001.06 1.06l1.06-1.06zM6.464 14.596a.75.75 0 10-1.06-1.06l-1.06 1.06a.75.75 0 001.06 1.06l1.06-1.06zM18 10a.75.75 0 01-.75.75h-1.5a.75.75 0 010-1.5h1.5A.75.75 0 0118 10zM5 10a.75.75 0 01-.75.75h-1.5a.75.75 0 010-1.5h1.5A.75.75 0 015 10zM14.596 15.657a.75.75 0 001.06-1.06l-1.06-1.061a.75.75 0 10-1.06 1.06l1.06 1.06zM5.404 6.464a.75.75 0 001.06-1.06l-1.06-1.06a.75.75 0 10-1.06 1.06l1.06 1.06z" />
          </svg>
          <svg v-else class="w-3.5 h-3.5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M7.455 2.004a.75.75 0 01.26.77 7 7 0 009.958 7.967.75.75 0 011.067.853A8.5 8.5 0 116.647 1.921a.75.75 0 01.808.083z" clip-rule="evenodd" />
          </svg>
        </button>
        <button class="footer-btn" @click="emit('openSettings')" title="Settings">
          <svg class="w-3.5 h-3.5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M7.84 1.804A1 1 0 018.82 1h2.36a1 1 0 01.98.804l.331 1.652a6.993 6.993 0 011.929 1.115l1.598-.54a1 1 0 011.186.447l1.18 2.044a1 1 0 01-.205 1.251l-1.267 1.113a7.047 7.047 0 010 2.228l1.267 1.113a1 1 0 01.206 1.25l-1.18 2.045a1 1 0 01-1.187.447l-1.598-.54a6.993 6.993 0 01-1.929 1.115l-.33 1.652a1 1 0 01-.98.804H8.82a1 1 0 01-.98-.804l-.331-1.652a6.993 6.993 0 01-1.929-1.115l-1.598.54a1 1 0 01-1.186-.447l-1.18-2.044a1 1 0 01.205-1.251l1.267-1.114a7.05 7.05 0 010-2.227L1.821 7.773a1 1 0 01-.206-1.25l1.18-2.045a1 1 0 011.187-.447l1.598.54A6.993 6.993 0 017.51 3.456l.33-1.652zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd" />
          </svg>
        </button>
      </div>
    </div>
  </aside>
</template>

<style scoped>
.sidebar {
  width: var(--sidebar-width);
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  position: relative;
  background: var(--color-background);
}

.sidebar-header {
  padding: 8px 12px 6px;
}

.new-task-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  width: 100%;
  padding: 9px 0;
  border: 1px solid var(--color-border);
  background: var(--color-surface);
  border-radius: var(--radius-lg);
  font-size: 13px;
  font-weight: 500;
  color: var(--color-foreground);
  cursor: pointer;
  transition: border-color 0.15s, box-shadow 0.15s, transform 0.08s var(--ease-out);
}
.new-task-btn:hover {
  border-color: color-mix(in srgb, var(--color-foreground) 32%, var(--color-border));
  box-shadow: var(--shadow-sm);
}
.new-task-btn:active {
  transform: translateY(0.5px);
}

/* ─── Tree ─── */
.tree {
  flex: 1;
  overflow-y: auto;
  padding: 4px 8px 8px;
}

.tree-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 6px 6px 4px;
}
.tree-label {
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--color-muted-foreground);
}
.tree-head-actions {
  display: flex;
  gap: 2px;
}
.tree-icon-btn {
  display: grid;
  place-items: center;
  width: 22px;
  height: 22px;
  border: none;
  background: transparent;
  border-radius: var(--radius-sm);
  color: var(--color-muted-foreground);
  cursor: pointer;
  transition: background 0.15s, color 0.15s;
}
.tree-icon-btn:hover {
  background: var(--color-muted);
  color: var(--color-foreground);
}
.tree-icon-btn.on {
  color: var(--color-primary);
}

.empty-state {
  text-align: center;
  font-size: 11px;
  padding: 24px 0;
  color: var(--color-muted-foreground);
}

.project-group {
  margin-bottom: 2px;
}

.project-row {
  display: flex;
  align-items: center;
  gap: 6px;
  width: 100%;
  padding: 8px 6px;
  border: none;
  background: transparent;
  border-radius: var(--radius-md);
  cursor: pointer;
  text-align: left;
  transition: background 0.15s;
}
.project-row:hover {
  background: var(--color-muted);
}
.proj-chevron {
  color: var(--color-muted-foreground);
  flex-shrink: 0;
  transition: transform 0.15s;
}
.proj-chevron.open {
  transform: rotate(90deg);
}
.proj-icon {
  color: var(--color-muted-foreground);
  flex-shrink: 0;
}
.project-row.active .proj-icon {
  color: var(--color-primary);
}
.proj-name {
  flex: 1;
  min-width: 0;
  font-size: 13px;
  font-weight: 500;
  color: var(--color-foreground);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.proj-count {
  font-size: 10px;
  font-family: var(--font-mono);
  color: var(--color-muted-foreground);
  flex-shrink: 0;
}

.task-list {
  padding-left: 14px;
}
.task-empty {
  font-size: 11px;
  color: var(--color-muted-foreground);
  padding: 5px 8px;
}

.task-row {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 8px 8px;
  margin-left: 6px;
  border-left: 1px solid var(--color-border);
  cursor: pointer;
  transition: background 0.15s;
  position: relative;
}
.task-row:hover {
  background: var(--color-muted);
}
.task-row.active {
  background: var(--accent-wash-soft);
  border-left-color: var(--color-primary);
}
.task-row.archived {
  opacity: 0.55;
}

.task-dot {
  width: 6px;
  height: 6px;
  border-radius: var(--radius-pill);
  flex-shrink: 0;
  background: transparent;
}
.task-dot.unread {
  background: var(--color-primary);
}
.task-pin {
  color: var(--color-primary);
  flex-shrink: 0;
}
.task-title {
  flex: 1;
  min-width: 0;
  font-size: 13px;
  color: var(--color-foreground);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.task-time {
  font-size: 10px;
  font-family: var(--font-mono);
  color: var(--color-muted-foreground);
  flex-shrink: 0;
}

/* ─── Task action menu ─── */
.task-menu {
  position: relative;
  display: inline-flex;
  flex-shrink: 0;
}
.task-menu-btn {
  display: grid;
  place-items: center;
  width: 20px;
  height: 20px;
  border: none;
  background: transparent;
  border-radius: var(--radius-sm);
  color: var(--color-muted-foreground);
  cursor: pointer;
  opacity: 0;
  transition: opacity 0.15s, background 0.15s, color 0.15s;
}
.task-row:hover .task-menu-btn {
  opacity: 1;
}
.task-menu-btn:hover {
  background: var(--color-secondary);
  color: var(--color-foreground);
}
.task-menu-items.flip-up {
  top: auto;
  bottom: calc(100% + 4px);
}
.task-menu-items {
  position: absolute;
  top: calc(100% + 4px);
  right: 0;
  min-width: 160px;
  padding: 4px;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-md);
  z-index: var(--z-dropdown);
  outline: none;
}
.tmi {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  padding: 7px 8px;
  border: none;
  background: transparent;
  border-radius: var(--radius-md);
  color: var(--color-foreground);
  font-size: 12.5px;
  text-align: left;
  cursor: pointer;
}
.tmi.hl {
  background: var(--color-muted);
}
.tmi.danger {
  color: var(--color-destructive);
}
.tmi-sep {
  height: 1px;
  margin: 4px 0;
  background: var(--color-border);
}

.pop-enter-active,
.pop-leave-active {
  transition: opacity 0.12s ease, transform 0.12s ease;
}
.pop-enter-from,
.pop-leave-to {
  opacity: 0;
  transform: translateY(-4px);
}

/* ─── Footer ─── */
.sidebar-footer {
  padding: 10px 12px;
  display: flex;
  align-items: center;
  justify-content: flex-end;
}
.footer-actions {
  display: flex;
  align-items: center;
  gap: 2px;
}
.footer-btn {
  width: 34px;
  height: 34px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius-md);
  border: none;
  background: transparent;
  color: var(--color-muted-foreground);
  cursor: pointer;
  transition: background 0.15s, color 0.15s;
}
.footer-btn:hover {
  background: var(--color-muted);
}
.footer-btn svg {
  width: 18px;
  height: 18px;
}
.footer-btn:hover {
  color: var(--color-foreground);
}
</style>
