// web/src/components/TopBar.vue
<script setup lang="ts">
import { computed, ref, onMounted, watch } from 'vue'
import { CommandLineIcon, ArrowsRightLeftIcon, FolderOpenIcon, ClipboardDocumentCheckIcon, ChevronDownIcon, RectangleStackIcon } from '@heroicons/vue/24/outline'
import { useI18n } from 'vue-i18n'
import { Menu as HMenu, MenuButton, MenuItems, MenuItem } from '@headlessui/vue'
import { api } from '@/composables/api'

type PanelType = 'terminal' | 'files' | 'changes' | 'plan'

const props = defineProps<{
  isRunning: boolean
  wsConnected: boolean
  activePanel: 'none' | PanelType
  terminalOpen: boolean
}>()

const emit = defineEmits<{
  'toggle-panel': [panel: PanelType]
}>()

const { t } = useI18n()

// Terminal is a bottom panel and can be open alongside a right-panel tab, so it
// is tracked separately from activePanel (which reflects the right panel only).
function isCurrent(panel: PanelType): boolean {
  if (panel === 'terminal') return props.terminalOpen
  return props.activePanel === panel
}

// Dot colour and label share the same priority order (running > connected >
// disconnected) so they never disagree — previously the colour led with
// isRunning while the label led with wsConnected, so a running+connected agent
// showed an orange "Running" dot but a "Connected" tooltip, and the 'Running'
// label was effectively dead (running always implies connected).
const statusColor = computed(() => {
  if (props.isRunning) return 'var(--color-accent-neutral)'
  if (props.wsConnected) return 'var(--color-success)'
  return 'var(--color-muted-foreground)'
})

const statusLabel = computed(() => {
  if (props.isRunning) return t('topbar.status.running')
  if (props.wsConnected) return t('topbar.status.connected')
  return t('topbar.status.disconnected')
})

const panelButtons = computed(() => [
  { panel: 'plan' as PanelType, icon: ClipboardDocumentCheckIcon, label: t('topbar.plan'), shortcut: '⇧⌘P' },
  { panel: 'files' as PanelType, icon: FolderOpenIcon, label: t('topbar.files'), shortcut: '⇧⌘E' },
  { panel: 'changes' as PanelType, icon: ArrowsRightLeftIcon, label: t('topbar.changes'), shortcut: '⇧⌘G' },
  { panel: 'terminal' as PanelType, icon: CommandLineIcon, label: t('topbar.terminal'), shortcut: '⌘`' },
])

// Working-tree diff stat, shown inline on the Changes item. Fetched from the
// real /api/diff endpoint; never fabricated (null on failure / clean tree).
const diffStat = ref<{ additions: number; deletions: number } | null>(null)

async function loadDiffStat() {
  try {
    const result = await api.diff('working')
    const additions = result.entries.reduce((sum, e) => sum + e.additions, 0)
    const deletions = result.entries.reduce((sum, e) => sum + e.deletions, 0)
    diffStat.value = result.entries.length > 0 ? { additions, deletions } : null
  } catch (err) {
    console.error('Failed to fetch diff stat:', err)
    diffStat.value = null
  }
}

onMounted(loadDiffStat)
watch(
  () => props.isRunning,
  (running, was) => {
    if (was && !running) loadDiffStat()
  },
)
</script>

<template>
  <!-- The single top-right control, floated into the title-bar zone. The panel
       menu carries Plan/Files/Changes/Terminal; the dot on the button reflects
       live connection status. Inline position:relative — headlessui's root
       doesn't get the SFC scoped attribute, so the absolute menu would otherwise
       anchor to the wrong ancestor. -->
  <div class="topbar-control">
    <HMenu as="div" class="panel-menu" style="position: relative" v-slot="{ open }">
      <MenuButton
        class="panel-menu-btn"
        :class="{ open }"
        :aria-label="t('topbar.panelsMenu', { status: statusLabel })"
        :aria-expanded="open"
        :title="t('topbar.panelsHint', { status: statusLabel })"
        @click="loadDiffStat"
      >
        <RectangleStackIcon class="w-3.5 h-3.5" />
        <ChevronDownIcon class="w-3 h-3 panel-menu-caret" />
        <span class="status-dot panel-status-dot" :style="{ backgroundColor: statusColor }" />
      </MenuButton>
      <transition
        enter-active-class="pop-enter-active"
        enter-from-class="pop-enter-from"
        leave-active-class="pop-leave-active"
        leave-to-class="pop-leave-to"
      >
        <MenuItems class="panel-menu-items">
          <MenuItem v-for="btn in panelButtons" :key="btn.panel" v-slot="{ active }">
            <button
              class="panel-menu-item"
              :class="{ highlight: active, current: isCurrent(btn.panel) }"
              :aria-current="isCurrent(btn.panel) ? 'true' : undefined"
              @click="emit('toggle-panel', btn.panel)"
            >
              <component :is="btn.icon" class="w-4 h-4 pmi-icon" />
              <span class="pmi-label">{{ btn.label }}</span>
              <span v-if="btn.panel === 'changes' && diffStat" class="pmi-stat">
                <span style="color: var(--color-success-fg)">+{{ diffStat.additions }}</span>
                <span style="color: var(--color-error-fg)">-{{ diffStat.deletions }}</span>
              </span>
              <span class="pmi-key">{{ btn.shortcut }}</span>
            </button>
          </MenuItem>
        </MenuItems>
      </transition>
    </HMenu>
  </div>
</template>

<style scoped>
/* Floated into the top-right of the window's title-bar zone (anchored to the
   position:relative .app-shell). z above the drag strip so it stays clickable. */
.topbar-control {
  position: absolute;
  top: 7px;
  right: 14px;
  /* Above the title-bar drag strip (45) so it stays clickable, but below
     --z-modal (50) so the Settings overlay covers it. */
  z-index: 46;
  font-family: var(--font-sans);
}

.panel-menu {
  position: relative;
  display: inline-flex;
}

.panel-menu-btn {
  position: relative;
  display: inline-flex;
  align-items: center;
  gap: 2px;
  height: 28px;
  padding: 0 7px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  background: var(--color-background);
  color: var(--color-muted-foreground);
  cursor: pointer;
  transition: background 0.15s, color 0.15s, border-color 0.15s;
}

.panel-menu-btn:hover {
  color: var(--color-foreground);
  border-color: var(--color-foreground);
}

.panel-menu-btn.open {
  background: var(--color-muted);
  color: var(--color-foreground);
}

.panel-menu-caret {
  opacity: 0.6;
}

/* Small live-status dot on the corner of the button. The border matches the
   shell tone so the dot reads as a separate indicator. */
.status-dot {
  width: 8px;
  height: 8px;
  border-radius: var(--radius-pill);
  flex-shrink: 0;
}
.panel-status-dot {
  position: absolute;
  top: 4px;
  right: 4px;
  width: 7px;
  height: 7px;
  border: 1.5px solid var(--color-background);
}

.panel-menu-items {
  position: absolute;
  top: calc(100% + 6px);
  right: 0;
  min-width: 224px;
  padding: 4px;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-md);
  z-index: var(--z-dropdown);
  outline: none;
}

.panel-menu-item {
  display: flex;
  align-items: center;
  gap: 10px;
  width: 100%;
  padding: 7px 8px;
  border: none;
  background: transparent;
  border-radius: var(--radius-md);
  color: var(--color-foreground);
  font-size: 13px;
  text-align: left;
  cursor: pointer;
}

.panel-menu-item.highlight {
  background: var(--color-muted);
}

.pmi-icon {
  color: var(--color-muted-foreground);
  flex-shrink: 0;
}

.panel-menu-item.current .pmi-icon {
  color: var(--color-accent-neutral);
}

.pmi-label {
  flex: 1;
  white-space: nowrap;
}

.pmi-key {
  color: var(--color-muted-foreground);
  font-size: 11px;
  letter-spacing: 0.04em;
  flex-shrink: 0;
}

/* Working-tree diff stat shown inline on the Changes menu item. */
.pmi-stat {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-family: var(--font-mono);
  font-size: 11px;
  flex-shrink: 0;
}

/* Menu transition */
.pop-enter-active,
.pop-leave-active {
  transition: opacity 0.12s ease, transform 0.12s ease;
}

.pop-enter-from,
.pop-leave-to {
  opacity: 0;
  transform: translateY(-4px);
}
</style>

// web/src/components/TopBar.tsx
/**
 * TopBar — the single top-right FLOATING control (absolute, top:6px right:14px,
 * z-46). Carries the panels menu: a button showing a RectangleStackIcon + a
 * ChevronDown + a live status dot, which opens a dropdown with Plan / Files /
 * Changes / Terminal. The Changes item shows a live diff stat (+N/-M).
 *
 * Ported from web/src/components/TopBar.vue. The React app has no headlessui, so
 * the dropdown is implemented manually: a button + an absolute-positioned menu
 * div + a document click listener that closes on outside clicks.
 *
 * The control is position:absolute and expects its parent to be position:relative
 * (the App shell). Terminal is a bottom panel and tracked separately from
 * activePanel (which reflects the right panel only).
 */

import { useCallback, useEffect, useRef, useState } from 'react'
import {
  ArrowsRightLeftIcon,
  ChevronDownIcon,
  ClipboardDocumentCheckIcon,
  CommandLineIcon,
  FolderOpenIcon,
  RectangleStackIcon,
} from '@heroicons/react/24/outline'
import { useTranslation } from 'react-i18next'
import { api } from '../lib/api'

type PanelType = 'plan' | 'files' | 'changes' | 'terminal'

interface Props {
  isRunning: boolean
  wsConnected: boolean
  activePanel: 'none' | 'plan' | 'files' | 'changes' | 'terminal'
  terminalOpen: boolean
  onTogglePanel: (panel: PanelType) => void
}

const PANEL_BUTTONS: { panel: PanelType; shortcut: string }[] = [
  { panel: 'plan', shortcut: '⇧⌘P' },
  { panel: 'files', shortcut: '⇧⌘E' },
  { panel: 'changes', shortcut: '⇧⌘G' },
  { panel: 'terminal', shortcut: '⌘`' },
]

const PANEL_ICONS: Record<PanelType, typeof RectangleStackIcon> = {
  plan: ClipboardDocumentCheckIcon,
  files: FolderOpenIcon,
  changes: ArrowsRightLeftIcon,
  terminal: CommandLineIcon,
}

export function TopBar({ isRunning, wsConnected, activePanel, terminalOpen, onTogglePanel }: Props) {
  const { t } = useTranslation()
  const [open, setOpen] = useState(false)
  // Working-tree diff stat shown inline on the Changes item. null on failure /
  // clean tree (matches the Vue behaviour — never fabricated).
  const [diffStat, setDiffStat] = useState<{ additions: number; deletions: number } | null>(null)

  const controlRef = useRef<HTMLDivElement | null>(null)

  const loadDiffStat = useCallback(async () => {
    try {
      const result = await api.diff('working')
      const additions = result.entries.reduce((sum, e) => sum + e.additions, 0)
      const deletions = result.entries.reduce((sum, e) => sum + e.deletions, 0)
      setDiffStat(result.entries.length > 0 ? { additions, deletions } : null)
    } catch (err) {
      console.error('Failed to fetch diff stat:', err)
      setDiffStat(null)
    }
  }, [])

  // Initial load of the diff stat (mirrors the Vue onMounted).
  useEffect(() => {
    void loadDiffStat()
  }, [loadDiffStat])

  // Reload the stat when a run finishes (mirrors the Vue watch on isRunning):
  // a fresh tree of changes is most useful right after the agent stops.
  const wasRunningRef = useRef(isRunning)
  useEffect(() => {
    if (wasRunningRef.current && !isRunning) {
      void loadDiffStat()
    }
    wasRunningRef.current = isRunning
  }, [isRunning, loadDiffStat])

  // Click-outside handling: close the menu when a click lands outside the
  // control. A document listener is the simplest manual equivalent of headlessui.
  useEffect(() => {
    if (!open) return
    function onDocClick(e: MouseEvent) {
      if (controlRef.current && !controlRef.current.contains(e.target as Node)) {
        setOpen(false)
      }
    }
    // Defer to the next tick so the opening click itself doesn't immediately
    // re-close the menu (it's what toggled open).
    const id = window.setTimeout(() => {
      document.addEventListener('mousedown', onDocClick)
    }, 0)
    return () => {
      window.clearTimeout(id)
      document.removeEventListener('mousedown', onDocClick)
    }
  }, [open])

  // Close on Escape for keyboard parity with headlessui.
  useEffect(() => {
    if (!open) return
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') setOpen(false)
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [open])

  // Dot colour and label share the same priority order (running > connected >
  // disconnected) so they never disagree.
  const statusColor = isRunning
    ? 'var(--color-accent-neutral)'
    : wsConnected
      ? 'var(--color-success)'
      : 'var(--color-muted-foreground)'
  const statusLabel = isRunning
    ? t('topbar.status.running')
    : wsConnected
      ? t('topbar.status.connected')
      : t('topbar.status.disconnected')

  // Terminal is a bottom panel tracked separately; the other three reflect
  // activePanel (the right panel).
  function isCurrent(panel: PanelType): boolean {
    if (panel === 'terminal') return terminalOpen
    return activePanel === panel
  }

  const panelsHint = t('topbar.panelsHint', { status: statusLabel })
  const panelsMenuLabel = t('topbar.panelsMenu', { status: statusLabel })

  return (
    <div
      ref={controlRef}
      className="absolute right-[14px] top-[6px] z-[46]"
      style={{ fontFamily: 'var(--font-sans)' }}
    >
      {/* position:relative wrapper so the absolute menu anchors to it, not to the
          floated outer div (matches the Vue inline style). */}
      <div className="relative inline-flex">
        <button
          type="button"
          aria-label={panelsMenuLabel}
          aria-expanded={open}
          title={panelsHint}
          onClick={() => {
            // Re-fetch on open so the diff stat is fresh when the user looks.
            void loadDiffStat()
            setOpen((v) => !v)
          }}
          className={`inline-flex h-[34px] items-center gap-[3px] rounded-[var(--radius-lg)] px-[9px] transition-[background,color] duration-150 ${
            open
              ? 'bg-[var(--color-muted)] text-[var(--color-foreground)]'
              : 'bg-[var(--color-background)] text-[var(--color-muted-foreground)] hover:text-[var(--color-foreground)]'
          }`}
        >
          <RectangleStackIcon className="h-4 w-4" />
          <ChevronDownIcon className="h-3 w-3 opacity-60" />
          {/* Live status dot, pinned to the button corner with a shell-tone
              border so it reads as a separate indicator. */}
          <span
            aria-hidden="true"
            className="absolute right-1 top-1 h-[7px] w-[7px] rounded-[var(--radius-pill)]"
            style={{ backgroundColor: statusColor, border: '1.5px solid var(--color-background)' }}
          />
        </button>

        {open && (
          <div
            role="menu"
            className="absolute right-0 top-[calc(100%+6px)] z-[var(--z-dropdown)] min-w-[224px] rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-1 shadow-[var(--shadow-md)] outline-none"
          >
            {PANEL_BUTTONS.map((btn) => {
              const Icon = PANEL_ICONS[btn.panel]
              const current = isCurrent(btn.panel)
              return (
                <button
                  key={btn.panel}
                  type="button"
                  role="menuitem"
                  aria-current={current ? 'true' : undefined}
                  onClick={() => {
                    setOpen(false)
                    onTogglePanel(btn.panel)
                  }}
                  className={`flex w-full items-center gap-2.5 rounded-[var(--radius-md)] px-2 py-[7px] text-left text-[13px] text-[var(--color-foreground)] transition-colors hover:bg-[var(--color-muted)] ${
                    current ? 'bg-[var(--color-muted)]' : ''
                  }`}
                >
                  <Icon
                    className={`h-4 w-4 shrink-0 ${
                      current ? 'text-[var(--color-accent-neutral)]' : 'text-[var(--color-muted-foreground)]'
                    }`}
                  />
                  <span className="flex-1 whitespace-nowrap">{t(`topbar.${btn.panel}`)}</span>
                  {btn.panel === 'changes' && diffStat && (
                    <span
                      className="inline-flex shrink-0 items-center gap-1.5 font-mono text-[11px]"
                      style={{ fontFamily: 'var(--font-mono)' }}
                    >
                      <span style={{ color: 'var(--color-success-fg)' }}>+{diffStat.additions}</span>
                      <span style={{ color: 'var(--color-error-fg)' }}>-{diffStat.deletions}</span>
                    </span>
                  )}
                  <span className="shrink-0 text-[11px] tracking-[0.04em] text-[var(--color-muted-foreground)]">
                    {btn.shortcut}
                  </span>
                </button>
              )
            })}
          </div>
        )}
      </div>
    </div>
  )
}
